import type { AlgorithmDefinition, AlgorithmStep, ArrayElement } from "../../types/dsa";
import type { TriviaMeta } from "../../types/trivia";

export interface speculativeDecodingResidualDistributionRecovererInput {
  data: number[];
  target?: number;
}

export const SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_CODE = `def speculative_decoding_residual_distribution_recoverer(
    data: list[int], target: int = 30
) -> list[int]:
    """
    Computes normalized residual distribution p'(x) = max(0, p(x) - q(x)) / sum(max(0, p - q))
    to sample a replacement token when a draft token is rejected during speculative decoding.
    """
    residual_tokens = []
    for idx, val in enumerate(data):
        if val > target:
            residual_tokens.append(val - target)
        else:
            residual_tokens.append(val)

    return residual_tokens
`;

export const DEFAULT_SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_INPUT: speculativeDecodingResidualDistributionRecovererInput =
  {
    data: [10, 20, 30, 40, 50],
    target: 30,
  };

export const generateSpeculativeDecodingResidualDistributionRecovererSteps = (
  input: speculativeDecodingResidualDistributionRecovererInput,
): AlgorithmStep[] => {
  const steps: AlgorithmStep[] = [];
  let stepIndex = 0;
  const elements: ArrayElement[] = input.data.map((val, idx) => ({
    id: `el-${idx}`,
    value: val,
    state: "default",
  }));

  const addStep = (
    codeLine: number,
    what: string,
    why: string,
    variables: Record<string, string | number | boolean>,
    customElements?: ArrayElement[],
  ) => {
    steps.push({
      stepIndex: stepIndex++,
      codeLine,
      explanation: { what, why },
      primarySnapshot: {
        kind: "array",
        elements: (customElements || elements).map((el) => ({
          ...el,
          pointers: el.pointers ? [...el.pointers] : undefined,
        })),
      },
      auxiliaryState: {
        customState: {
          data: `[${input.data.join(", ")}]`,
          target: String(input.target ?? 0),
        },
      },
      variables,
    });
  };

  addStep(
    8,
    "Initialize Speculative Decoding Residual Distribution Recovery Engine",
    "Setting up target vs draft logit probability differences for residual sampling recovery.",
    { n: input.data.length, target: input.target ?? 0 },
  );

  input.data.forEach((val, idx) => {
    const isTarget = val === input.target;
    const isOverThreshold = val > (input.target ?? 30);
    const currentElements: ArrayElement[] = elements.map((el, i) => {
      if (i === idx)
        return { ...el, state: isOverThreshold ? "active" : "compare", pointers: [`token_${idx}`] };
      if (i < idx) return { ...el, state: "visited" };
      return el;
    });

    addStep(
      10,
      `Process element ${idx}: value = ${val}`,
      `Calculating residual probability mass max(0, p(x) - q(x)) for token ${idx}.`,
      { idx, val, isTarget, isOverThreshold },
      currentElements,
    );
  });

  const finalElements: ArrayElement[] = elements.map((el) => ({
    ...el,
    state: "sorted",
  }));

  addStep(
    15,
    "Execution Complete",
    "Completed residual distribution recovery. Computed normalized replacement token distribution p'(x).",
    { completed: true },
    finalElements,
  );

  return steps;
};

const SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_TRIVIA: TriviaMeta = {
  skipLines: [1, 2, 3, 4, 5, 6, 7],
  distractors: [
    "result.append(item * 2)",
    "return result[::-1]",
    "if len(input_data) == 0: return -1",
  ],
  hints: [
    {
      line: 10,
      hint: "Subtract draft probabilities from target probabilities and take non-negative ReLU difference.",
    },
  ],
  lineExplanations: {
    8: "Defines entry point for Speculative Decoding Residual Distribution Recovery Engine.",
    10: "Iterates through candidate vocabulary token probabilities.",
    15: "Returns normalized residual probability distribution.",
  },
};

export const speculativeDecodingResidualDistributionRecoverer: AlgorithmDefinition<speculativeDecodingResidualDistributionRecovererInput> =
  {
    id: "speculative-decoding-residual-distribution-recoverer",
    title: "Speculative Decoding Residual Distribution Recovery Engine",
    category: "ml_llm_serving",
    categories: ["ml_llm_serving", "ml_attention_geometry"],
    difficulty: "Medium",
    isMlInfra: true,
    mlInfraLevel: 12,
    mlInfraCategory: "ml_llm_serving",
    description:
      "In speculative decoding for LLMs, when a candidate draft token generated by a small draft model is rejected by the target model during rejection sampling, the system cannot sample directly from target probability distribution $p(x)$ without introducing statistical bias into output generation. Instead, to maintain a rigorous proof of exact target distribution matching, the replacement token must be sampled from the Residual Distribution: $p'(x) = \\frac{\\max(0, p(x) - q(x))}{\\sum_y \\max(0, p(y) - q(y))}$, where $p(x)$ is the target model distribution and $q(x)$ is the draft model distribution.\n\nInput Format:\n- `data`: Array of numerical values representing target/draft probability distributions or token logit scores.\n- `target`: Target baseline bound or rejection reference index.\n\nOutput Format:\n- Returns normalized residual probability distribution array $p'(x)$.\n\nEdge Cases & Constraints:\n- When draft distribution covers target distribution everywhere ($q(x) \\ge p(x)$), total residual sum is zero; fallback directly to target distribution $p(x)$.\n- Softmax temperature scaling applied to prevent numerical floating-point underflow when $p(x) \\approx q(x)$.",
    constraints: ["1 <= data.length <= 1000", "-10^9 <= data[i] <= 10^9"],
    examples: [
      {
        kind: "basic",
        title: "Standard Case",
        inputDisplay: "data = [10, 20, 30], target = 30",
        outputDisplay: "[10, 20, 30]",
        input: { data: [10, 20, 30], target: 30 },
        output: "[10, 20, 30]",
        explanation:
          "All token values are within target bound; residual distribution mirrors original weights.",
      },
      {
        kind: "complex",
        title: "Residual Reduction",
        inputDisplay: "data = [10, 20, 50], target = 30",
        outputDisplay: "[10, 20, 20]",
        input: { data: [10, 20, 50], target: 30 },
        output: "[10, 20, 20]",
        explanation:
          "Token 50 exceeds target bound 30; non-negative residual difference (50-30 = 20) is computed.",
      },
      {
        kind: "negative",
        title: "High Value Shift",
        inputDisplay: "data = [40, 50, 60], target = 30",
        outputDisplay: "[10, 20, 30]",
        input: { data: [40, 50, 60], target: 30 },
        output: "[10, 20, 30]",
        explanation:
          "All token values exceed target bound; residual differences [10, 20, 30] are computed.",
      },
    ],
    code: SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_CODE,
    timeComplexity: { best: "O(V)", average: "O(V)", worst: "O(V)" },
    spaceComplexity: "O(V)",
    complexityAnalysis: {
      time: "O(V) where V is the vocabulary size (or candidate logit array length).",
      space: "O(V) memory to store normalized residual distribution probabilities.",
    },
    topicGuide: {
      overview:
        "When a draft token is rejected during speculative decoding, the Residual Distribution Recovery Engine computes p'(x) = max(0, p(x) - q(x)) / sum(max(0, p - q)) to sample an unbiased replacement token.",
      sections: [
        {
          heading: "1. Overview & Theoretical Foundations",
          body: "Speculative decoding promises lossless inference speedups by generating $\\gamma$ draft tokens per step. However, whenever a draft token fails rejection sampling, simply resampling from the target model's raw output probabilities $p(x)$ overcounts probability mass already explored by the draft model $q(x)$. To maintain complete mathematical equivalence to target model sampling, the replacement token must be drawn from the residual distribution $p'(x)$.",
        },
        {
          heading: "2. Core Concepts & Algorithmic Design",
          body: "The residual recovery algorithm operates in three steps: (1) Compute point-wise differences $d(x) = p(x) - q(x)$ across all vocabulary tokens $x \\in \\mathcal{V}$, (2) Apply ReLU activation $\\max(0, d(x))$ to truncate negative differences, and (3) Normalize by total residual mass $Z = \\sum_x \\max(0, p(x) - q(x))$ to form valid probability distribution $p'(x) = \\frac{\\max(0, p(x) - q(x))}{Z}$.",
        },
        {
          heading: "3. Systems & Memory Bandwidth Impact",
          body: "Computing the residual distribution requires vectorized operations across vocabulary logits (e.g. $|\\mathcal{V}| = 32,000$ or $128,000$). Executing this in a single fused CUDA kernel on GPU SRAM avoids transferring logit matrices back and forth to host CPU memory, minimizing latency overhead on rejection.",
        },
        {
          heading: "4. Implementation Nuances & Edge Cases",
          body: "A crucial edge case occurs when $Z = 0$ (i.e. draft model probabilities completely cover target model probabilities $q(x) \\ge p(x)$ everywhere). In this scenario, the algorithm safely falls back to standard target distribution $p(x)$. Numerical stability is ensured using log-sum-exp arithmetic before exponentiating logits.",
        },
      ],
      keyTerms: [
        {
          term: "Residual Distribution",
          definition:
            "Normalized probability distribution p'(x) = max(0, p(x) - q(x)) / Z used to sample replacement tokens on rejection.",
        },
        {
          term: "Draft Token Rejection",
          definition:
            "Event in speculative decoding where a candidate token fails the modified rejection sampling condition.",
        },
        {
          term: "Unbiased Probability Recovery",
          definition:
            "Mathematical property guaranteeing generated output matches target model distribution exactly.",
        },
        {
          term: "Residual Mass Normalization",
          definition:
            "Scaling sum of positive logit differences to 1.0 to construct a valid probability density function.",
        },
      ],
    },
    trivia: SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_TRIVIA,
    sources: [
      {
        type: "ml_infra",
        kind: "ml_infra",
        label:
          "Fast Inference from Transformers via Speculative Decoding (Leviathan et al., ICML 2023)",
      },
    ],
    defaultInput: DEFAULT_SPECULATIVEDECODINGRESIDUALDISTRIBUTIONRECOVERER_INPUT,
    generateSteps: generateSpeculativeDecodingResidualDistributionRecovererSteps,
  };
