import type { AlgorithmDefinition, AlgorithmStep, ArrayElement } from "../../types/dsa";
import type { TriviaMeta } from "../../types/trivia";

export interface targetModelParallelVerificationPassInput {
  data: number[];
  target?: number;
}

export const TARGETMODELPARALLELVERIFICATIONPASS_CODE = `def target_model_parallel_verification_pass(
    draft_tokens: list[int], target_threshold: int = 30
) -> list[bool]:
    """
    Executes a single parallel target model forward pass verifying all gamma draft tokens
    concurrently, evaluating acceptance criteria sequentially up to first rejection.
    """
    verification_results = []
    for pos, token in enumerate(draft_tokens):
        if token <= target_threshold:
            verification_results.append(True)
        else:
            verification_results.append(False)
            break

    return verification_results
`;

export const DEFAULT_TARGETMODELPARALLELVERIFICATIONPASS_INPUT: targetModelParallelVerificationPassInput =
  {
    data: [10, 20, 30, 40, 50],
    target: 30,
  };

export const generateTargetModelParallelVerificationPassSteps = (
  input: targetModelParallelVerificationPassInput,
): AlgorithmStep[] => {
  const steps: AlgorithmStep[] = [];
  let stepIndex = 0;
  const elements: ArrayElement[] = input.data.map((val, idx) => ({
    id: `el-${idx}`,
    value: val,
    state: "default",
  }));

  const addStep = (
    codeLine: number,
    what: string,
    why: string,
    variables: Record<string, string | number | boolean>,
    customElements?: ArrayElement[],
  ) => {
    steps.push({
      stepIndex: stepIndex++,
      codeLine,
      explanation: { what, why },
      primarySnapshot: {
        kind: "array",
        elements: (customElements || elements).map((el) => ({
          ...el,
          pointers: el.pointers ? [...el.pointers] : undefined,
        })),
      },
      auxiliaryState: {
        customState: {
          data: `[${input.data.join(", ")}]`,
          target: String(input.target ?? 0),
        },
      },
      variables,
    });
  };

  addStep(
    8,
    "Initialize Speculative Decoding Target Model Parallel Verification Pass",
    "Setting up target model parallel forward pass layout to verify candidate draft tokens in batch.",
    { n: input.data.length, target: input.target ?? 0 },
  );

  input.data.forEach((val, idx) => {
    const isTarget = val === input.target;
    const isAccepted = val <= (input.target ?? 30);
    const currentElements: ArrayElement[] = elements.map((el, i) => {
      if (i === idx)
        return { ...el, state: isAccepted ? "active" : "compare", pointers: [`gamma_${idx}`] };
      if (i < idx) return { ...el, state: "visited" };
      return el;
    });

    addStep(
      10,
      `Process element ${idx}: value = ${val}`,
      `Verifying draft token at speculative position ${idx}. Accepted = ${isAccepted}.`,
      { idx, val, isTarget, isAccepted },
      currentElements,
    );
  });

  const finalElements: ArrayElement[] = elements.map((el) => ({
    ...el,
    state: "sorted",
  }));

  addStep(
    16,
    "Execution Complete",
    "Completed target model parallel verification pass. Returned accepted draft token mask.",
    { completed: true },
    finalElements,
  );

  return steps;
};

const TARGETMODELPARALLELVERIFICATIONPASS_TRIVIA: TriviaMeta = {
  skipLines: [1, 2, 3, 4, 5, 6, 7],
  distractors: [
    "result.append(item * 2)",
    "return result[::-1]",
    "if len(input_data) == 0: return -1",
  ],
  hints: [
    { line: 10, hint: "Verify draft tokens sequentially up to the first rejected position." },
  ],
  lineExplanations: {
    8: "Defines entry point for Speculative Decoding Target Model Parallel Verification Pass.",
    10: "Iterates through draft candidate tokens in parallel forward pass output.",
    16: "Returns verification boolean mask array.",
  },
};

export const targetModelParallelVerificationPass: AlgorithmDefinition<targetModelParallelVerificationPassInput> =
  {
    id: "target-model-parallel-verification-pass",
    title: "Speculative Decoding Target Model Parallel Verification Pass",
    category: "ml_llm_serving",
    categories: ["ml_llm_serving", "ml_distributed_systems"],
    difficulty: "Medium",
    isMlInfra: true,
    mlInfraLevel: 12,
    mlInfraCategory: "ml_llm_serving",
    description:
      "Speculative decoding speeds up LLM generation by replacing $\\gamma$ sequential forward passes of a large target model with $\\gamma$ fast forward passes of a small draft model, followed by a single parallel forward pass of the target model. During this parallel verification pass, the target model receives all $\\gamma$ candidate draft tokens in a single batched sequence, computing logits for every token position concurrently in parallel. The engine then inspects acceptance criteria sequentially, accepting tokens up to the first rejection point.\n\nInput Format:\n- `data`: Array of draft token IDs generated by the draft model during speculative lookahead.\n- `target`: Target verification threshold or rank index for parallel verification.\n\nOutput Format:\n- Returns boolean array indicating token acceptance up to first rejection boundary.\n\nEdge Cases & Constraints:\n- All $\\gamma$ tokens accepted: Maximum speedup ($\\gamma + 1$ total tokens generated in 1 target pass).\n- First token rejected: Target model still emits 1 valid replacement token from residual distribution.\n- Distributed Tensor Parallelism: Target logits across multiple GPU ranks must be synchronized via AllReduce before verification.",
    constraints: ["1 <= data.length <= 1000", "-10^9 <= data[i] <= 10^9"],
    examples: [
      {
        kind: "basic",
        title: "Standard Case",
        inputDisplay: "draft_tokens = [10, 20, 30], threshold = 30",
        outputDisplay: "[True, True, True]",
        input: { data: [10, 20, 30], target: 30 },
        output: "[True, True, True]",
        explanation: "All 3 draft tokens are verified and accepted in a single target model pass.",
      },
      {
        kind: "complex",
        title: "Early Rejection",
        inputDisplay: "draft_tokens = [10, 20, 50, 10], threshold = 30",
        outputDisplay: "[True, True, False]",
        input: { data: [10, 20, 50, 10], target: 30 },
        output: "[True, True, False]",
        explanation: "Token 50 at index 2 fails verification; acceptance halts early at index 2.",
      },
      {
        kind: "negative",
        title: "First Token Rejected",
        inputDisplay: "draft_tokens = [50, 10, 20], threshold = 30",
        outputDisplay: "[False]",
        input: { data: [50, 10, 20], target: 30 },
        output: "[False]",
        explanation: "First token fails verification immediately; 0 draft tokens accepted.",
      },
    ],
    code: TARGETMODELPARALLELVERIFICATIONPASS_CODE,
    timeComplexity: { best: "O(gamma)", average: "O(gamma)", worst: "O(gamma)" },
    spaceComplexity: "O(gamma)",
    complexityAnalysis: {
      time: "O(gamma) time to verify gamma draft tokens sequentially after 1 target model GEMM forward pass.",
      space: "O(gamma) memory to store verification output booleans.",
    },
    topicGuide: {
      overview:
        "The Target Model Parallel Verification Pass converts sequential autoregressive LLM decoding iterations into a single batched parallel forward pass across speculative draft tokens.",
      sections: [
        {
          heading: "1. Overview & Theoretical Foundations",
          body: "Standard LLM decoding generates 1 token per forward pass, causing low compute intensity (arithmetic intensity $\\approx 1$ FLOP/byte) because GPU Memory Bandwidth is spent loading model weights for every single token. Speculative decoding batches $\\gamma$ draft tokens into a single parallel forward pass on the target model. This transforms matrix-vector multiplications into matrix-matrix multiplications (GEMM), dramatically increasing Tensor Core utilization.",
        },
        {
          heading: "2. Core Concepts & Algorithmic Design",
          body: "During parallel verification: (1) The draft model sequentially generates $\\gamma$ tokens $x_1, x_2, \\dots, x_\\gamma$, (2) The target model executes a single forward pass over input sequence $[x_1, \\dots, x_\\gamma]$, producing logit distributions $p_1, \\dots, p_{\\gamma+1}$ simultaneously using causal attention masks, and (3) The engine sequentially checks rejection sampling criteria for each position $i \\in [1, \\gamma]$.",
        },
        {
          heading: "3. Systems & Memory Bandwidth Impact",
          body: "Evaluating $\\gamma$ draft tokens in 1 target pass increases batch size in the target GEMM kernels from 1 to $\\gamma$. GPU memory bandwidth utilization drops as FLOP-to-byte ratio rises, accelerating overall inference latency by 2x-3x on large models (e.g. LLaMA-70B).",
        },
        {
          heading: "4. Implementation Nuances & Edge Cases",
          body: "If a rejection occurs at position $k < \\gamma$, the KV cache entries for rejected tokens $x_{k+1}, \\dots, x_\\gamma$ must be rolled back or truncated in the block table. For tree-based speculative decoding (e.g. Medusa or SpecInfer), tree causal attention masks are constructed to verify multiple draft branches simultaneously.",
        },
      ],
      keyTerms: [
        {
          term: "Parallel Verification Pass",
          definition:
            "A single target model forward pass evaluating gamma speculative draft tokens concurrently.",
        },
        {
          term: "Speculative Horizon (gamma)",
          definition:
            "The number of candidate tokens generated by the draft model per verification iteration.",
        },
        {
          term: "Causal Mask Tree",
          definition:
            "Attention mask layout permitting parallel evaluation of tree-structured speculative draft tokens.",
        },
        {
          term: "KV Cache Rollback",
          definition:
            "Truncating physical block table pointers for speculatively generated tokens rejected by the target model.",
        },
      ],
    },
    trivia: TARGETMODELPARALLELVERIFICATIONPASS_TRIVIA,
    sources: [
      {
        type: "ml_infra",
        kind: "ml_infra",
        label:
          "Fast Inference from Transformers via Speculative Decoding (Leviathan et al., ICML 2023)",
      },
    ],
    defaultInput: DEFAULT_TARGETMODELPARALLELVERIFICATIONPASS_INPUT,
    generateSteps: generateTargetModelParallelVerificationPassSteps,
  };
