import { CategoryType } from "../types/dsa";

export const CATEGORIES: { id: CategoryType; label: string }[] = [
  { id: "arrays_and_hashing", label: "1. Arrays & Hashing" },
  { id: "two_pointers", label: "2. Two Pointers" },
  { id: "stack_and_queue", label: "3. Stack & Queue" },
  { id: "binary_search", label: "4. Binary Search" },
  { id: "sliding_window", label: "5. Sliding Window" },
  { id: "linked_list", label: "6. Linked List" },
  { id: "tree_fundamentals", label: "7. Tree Fundamentals" },
  { id: "tree_queries_and_diameter", label: "8. Tree Queries & Diameter" },
  { id: "tries_and_strings", label: "9. Tries & Strings" },
  { id: "heap_and_priority_queue", label: "10. Heap / Priority Queue" },
  { id: "backtracking", label: "11. Backtracking" },
  { id: "graph_traversal", label: "12. Graph Traversal" },
  { id: "graph_shortest_paths", label: "13. Graph Shortest Paths" },
  { id: "graph_spanning_trees", label: "14. Graph Spanning Trees" },
  { id: "graph_directed_and_scc", label: "15. Graph Directed & SCC" },
  { id: "graph_flows_and_cuts", label: "16. Graph Flows & Cuts" },
  { id: "dp_1d", label: "17. 1-D Dynamic Programming" },
  { id: "dp_2d", label: "18. 2-D Dynamic Programming" },
  { id: "intervals", label: "19. Intervals" },
  { id: "greedy_algorithms", label: "20. Greedy Algorithms" },
  { id: "bit_manipulation", label: "21. Bit Manipulation" },
  { id: "math_and_number_theory", label: "22. Math & Number Theory" },
  { id: "game_theory", label: "23. Game Theory" },
  { id: "advanced_range_queries", label: "24. Advanced Range Queries" },
  { id: "geometry_and_sweep_line", label: "25. Geometry & Sweep Line" },
  { id: "ml_tensor_algebra", label: "26. Tensor Memory & Strides" },
  { id: "ml_gemm_roofline", label: "27. GEMM & Roofline Model" },
  { id: "ml_autograd_dags", label: "28. Autograd & Computation Graphs" },
  { id: "ml_precision_quantization", label: "29. Precision Math & Quantization" },
  { id: "ml_vector_search", label: "30. Vector Search & Spatial Geometry" },
  { id: "ml_tokenization", label: "31. Subword Tokenization & Tries" },
  { id: "ml_tree_ensembles", label: "32. Tree Ensembles & XGBoost" },
  { id: "ml_convolutions", label: "33. Convolutional Tiling & im2col" },
  { id: "ml_recurrent_gates", label: "34. Recurrent Gates & Sequences" },
  { id: "ml_attention_geometry", label: "35. Attention Geometry & RoPE" },
  { id: "ml_hardware_kernels", label: "36. Hardware Kernels & Fusion" },
  { id: "ml_graph_compilers", label: "37. Model Compression & Compilers" },
  { id: "ml_distributed_systems", label: "38. Distributed ML & Interconnects" },
  { id: "ml_llm_serving", label: "39. LLM Serving & Continuous Batching" },
];

export const CATEGORY_LABELS: Record<string, string> = {
  arrays_and_hashing: "Arrays & Hashing",
  two_pointers: "Two Pointers",
  sliding_window: "Sliding Window",
  stack_and_queue: "Stack & Queue",
  binary_search: "Binary Search",
  linked_list: "Linked List",
  tree_fundamentals: "Tree Fundamentals",
  tree_queries_and_diameter: "Tree Queries & Diameter",
  tries_and_strings: "Tries & Strings",
  heap_and_priority_queue: "Heap / Priority Queue",
  backtracking: "Backtracking",
  graph_traversal: "Graph Traversal",
  graph_shortest_paths: "Graph Shortest Paths",
  graph_spanning_trees: "Graph Spanning Trees",
  graph_directed_and_scc: "Graph Directed & SCC",
  graph_flows_and_cuts: "Graph Flows & Cuts",
  dp_1d: "1-D Dynamic Programming",
  dp_2d: "2-D Dynamic Programming",
  intervals: "Intervals",
  greedy_algorithms: "Greedy Algorithms",
  bit_manipulation: "Bit Manipulation",
  math_and_number_theory: "Math & Number Theory",
  game_theory: "Game Theory",
  advanced_range_queries: "Advanced Range Queries",
  geometry_and_sweep_line: "Geometry & Sweep Line",
  ml_tensor_algebra: "Tensor Algebra & Memory Strides",
  ml_gemm_roofline: "GEMM & Roofline Model",
  ml_autograd_dags: "Autograd & Computational Graphs",
  ml_precision_quantization: "Precision Math & Quantization",
  ml_vector_search: "Vector Search & Spatial Indexing",
  ml_tokenization: "Subword Tokenization & Tries",
  ml_tree_ensembles: "Tree Ensembles & XGBoost",
  ml_convolutions: "Convolutional Tiling & im2col",
  ml_recurrent_gates: "Recurrent Gates & Sequences",
  ml_attention_geometry: "Attention Geometry & KV-Cache",
  ml_hardware_kernels: "Hardware Kernels & Fusion",
  ml_graph_compilers: "Model Compression & Compilers",
  ml_distributed_systems: "Distributed ML & Interconnects",
  ml_llm_serving: "LLM Serving & Continuous Batching",
};

const CATEGORY_ID_SET = new Set<string>(CATEGORIES.map((category) => category.id));

/* Narrowing guard for URL search params: only the canonical category ids above
   count — the legacy CategoryType aliases are not valid routeable filters. */
export function isCategoryType(
  value: string | number | boolean | null | undefined | object,
): value is CategoryType {
  return typeof value === "string" && CATEGORY_ID_SET.has(value);
}
