import type { CoursePage } from "../../../../courseTypes";

export const page2: CoursePage = {
  id: "dsa_dp_1d_c1_p2",
  pageNumber: 2,
  title: "Formal Proofs & 3-Stage Implementation Progression",
  sections: [
    {
      type: "math_proof",
      title:
        "Theorem 1: LIS Patience Sorting Correctness via Dilworth's Theorem (Aldous & Diaconis 1999)",
      theorem:
        "For any sequence of numbers $A = (a_1, a_2, \\dots, a_N)$, the number of piles $P$ generated by the greedy Patience Sorting algorithm is equal to the exact length $L$ of the Longest Increasing Subsequence (LIS) of $A$. Furthermore, patience sorting computes $L$ in strictly $O(N \\log N)$ time and $O(N)$ auxiliary space.",
      proof: `
**Proof via Poset Duality & Dilworth's Theorem:**
1. Define a partially ordered set (poset) $(A, \\prec)$ on sequence elements where:
   $$a_i \\prec a_j \\iff i < j \\quad \\text{and} \\quad a_i < a_j$$
2. In this poset:
   - A **Chain** is a sequence of elements where each element is strictly smaller and appears after the previous element—precisely an **Increasing Subsequence**.
   - An **Antichain** is a set of elements where no two elements are comparable under $\\prec$—which corresponds to a **Non-Increasing Subsequence** ($i < j \\implies a_i \\ge a_j$).
3. **Dilworth's Theorem (1950):** In any finite poset, the size of the maximum chain equals the minimum number of antichains needed to cover the poset:
   $$\\max |\\text{Chain}| = \\min |\\text{Antichain Partition}|$$
4. **Patience Sorting Mechanics:**
   - Patience sorting places each incoming card $a_k$ onto the leftmost pile whose top card is $\\ge a_k$. If no such pile exists, a new pile is created to the right.
   - Within each individual pile, cards are placed in non-increasing order from bottom to top ($a_{i_1} \\ge a_{i_2} \\ge \\dots$).
   - Therefore, each pile is a valid **Antichain** in the poset $(A, \\prec)$.
5. **Duality Equality:**
   - If patience sorting creates $P$ piles, it produces an explicit partition of $A$ into $P$ antichains.
   - When placing a card on pile $k > 1$, we can record a pointer to the current top card of pile $k - 1$ (which is strictly smaller than the incoming card).
   - Following these pointers backwards from any card on pile $P$ constructs an explicit increasing subsequence (chain) of length $P$.
   - Thus, $\\text{LIS}(A) \\ge P$.
   - By Dilworth's Theorem and the pigeonhole principle, no chain can contain more than one element from each antichain (pile), so $\\text{LIS}(A) \\le P$.
   - Hence, $\\text{LIS}(A) = P$.
6. **Complexity:** Since the top cards of the piles are always strictly increasing, finding the leftmost valid pile uses binary search ('lower_bound') in $O(\\log P) \\le O(\\log N)$ time per element, achieving total runtime $O(N \\log N)$. $\\blacksquare$
      `,
    },
    {
      type: "math_proof",
      title: "Theorem 2: Kadane's Maximum Subarray Sum Inductive Invariant",
      theorem:
        "For an array $A = (a_0, a_1, \\dots, a_{n-1})$, Kadane's recurrence $M[i] = \\max(a_i, M[i-1] + a_i)$ correctly computes the maximum contiguous subarray sum ending at index $i$, and $\\max_{0 \\le i < n} M[i]$ is the global maximum subarray sum, running in $\\Theta(n)$ time and $O(1)$ auxiliary space.",
      proof: `
**Proof by Mathematical Induction on Array Prefix Length:**
1. Let $S(i)$ denote the set of all non-empty contiguous subarrays of $A$ ending at index $i$:
   $$S(i) = \\{ (a_j, a_{j+1}, \\dots, a_i) \\mid 0 \\le j \\le i \\}$$
2. Define $M^*[i] = \\max_{B \\in S(i)} \\sum_{x \\in B} x$ as the true maximal sum of any subarray ending at $i$.
3. **Base Case ($i = 0$):**
   - $S(0) = \\{ (a_0) \\}$. The only subarray ending at 0 is $(a_0)$, with sum $a_0$.
   - $M[0] = a_0 = M^*[0]$. Base case holds.
4. **Inductive Step:** Assume $M[i-1] = M^*[i-1]$ holds for $i-1 \\ge 0$.
   - Any subarray $B \\in S(i)$ ending at $i$ either:
     - Contains only $a_i$ ($j = i$), with sum $a_i$.
     - Extends a non-empty subarray $B' \\in S(i-1)$ ($j < i$), with sum $(\\sum_{x \\in B'} x) + a_i$.
   - Maximizing over all $B \\in S(i)$:
     $$M^*[i] = \\max \\left( a_i, \\max_{B' \\in S(i-1)} \\left( \\sum_{x \\in B'} x + a_i \\right) \\right) = \\max(a_i, M^*[i-1] + a_i)$$
   - By the inductive hypothesis, $M^*[i-1] = M[i-1]$, so $M^*[i] = \\max(a_i, M[i-1] + a_i) = M[i]$.
5. The induction is complete. Since any non-empty contiguous subarray of $A$ must end at some index $i \\in \\{0, \\dots, n-1\\}$, the global maximum subarray sum is $\\max_{0 \\le i < n} M[i]$.
6. The state $M[i]$ depends only on $M[i-1]$, allowing memory compression to a single scalar variable in $O(1)$ space. $\\blacksquare$
      `,
    },
    {
      type: "code_progression",
      title: "3-Stage Code Progression",
      language: "typescript",
      stages: [
        {
          label: "Stage 1: Naive Recursive Memoized Baseline",
          code: `export function lengthOfLISNaive(nums: number[]): number {
  function solve(idx: number, prevIdx: number): number {
    if (idx === nums.length) return 0;

    // Option 1: Skip current element
    let maxLen = solve(idx + 1, prevIdx);

    // Option 2: Include current element if greater than previous
    if (prevIdx === -1 || nums[idx] > nums[prevIdx]) {
      const takeLen = 1 + solve(idx + 1, idx);
      if (takeLen > maxLen) maxLen = takeLen;
    }

    return maxLen;
  }

  return solve(0, -1);
}`,
          explanation:
            "Exhaustive recursive branch tree. Without memoization, runtime is strictly $\\Theta(2^N)$. Even with 2D memoization table `memo[N][N]`, execution consumes $O(N^2)$ time and $O(N^2)$ heap memory.",
          timeComplexity: "O(2^N) brute force / O(N^2) memoized",
          spaceComplexity: "O(N^2) auxiliary memory",
        },
        {
          label: "Stage 2: Space-Optimized Tabulated 1D DP (Rolling Arrays)",
          code: `export class DynamicProgramming1D {
  // Kadane's Algorithm: O(N) time and O(1) auxiliary space
  public static maxSubArray(nums: number[]): number {
    let currentSum = nums[0];
    let maxSum = nums[0];

    for (let i = 1; i < nums.length; i++) {
      currentSum = Math.max(nums[i], currentSum + nums[i]);
      if (currentSum > maxSum) maxSum = currentSum;
    }
    return maxSum;
  }

  // Coin Change (Minimum Coins): O(N * amount) time and O(amount) space
  public static coinChange(coins: number[], amount: number): number {
    const dp = new Int32Array(amount + 1).fill(amount + 1);
    dp[0] = 0;

    for (let i = 1; i <= amount; i++) {
      for (const coin of coins) {
        if (i >= coin) {
          const count = dp[i - coin] + 1;
          if (count < dp[i]) dp[i] = count;
        }
      }
    }
    return dp[amount] > amount ? -1 : dp[amount];
  }
}`,
          explanation:
            "Stage 2 replaces 2D tables with compact 1D rolling buffers. Kadane's algorithm maintains only 2 scalar registers, and Coin Change uses an `Int32Array` of size `amount + 1`.",
          timeComplexity: "Kadane: O(N), Coin Change: O(N * Amount)",
          spaceComplexity: "Kadane: O(1), Coin Change: O(Amount)",
        },
        {
          label: "Stage 3: Matrix Exponentiation Engine & Fast Patience LIS (O(N log N))",
          code: `export class FastDP1DEngine {
  // LIS in strictly O(N log N) using Patience Sorting Tails Array
  public static lengthOfLIS(nums: number[]): number {
    const n = nums.length;
    if (n === 0) return 0;
    const tails = new Int32Array(n);
    let len = 0;

    for (let i = 0; i < n; i++) {
      const x = nums[i];
      let left = 0;
      let right = len;

      // Binary search lower_bound: find first tail >= x
      while (left < right) {
        const mid = (left + right) >> 1;
        if (tails[mid] >= x) {
          right = mid;
        } else {
          left = mid + 1;
        }
      }

      tails[left] = x;
      if (left === len) len++;
    }
    return len;
  }

  // Matrix Exponentiation for N-th Fibonacci in O(log N) operations
  public static fibonacci(n: bigint, mod: bigint = 1000000007n): bigint {
    if (n === 0n) return 0n;
    if (n === 1n) return 1n;

    let res: [bigint, bigint, bigint, bigint] = [1n, 0n, 0n, 1n]; // Identity matrix
    let base: [bigint, bigint, bigint, bigint] = [1n, 1n, 1n, 0n]; // Fibonacci transition

    function multiply(
      A: [bigint, bigint, bigint, bigint],
      B: [bigint, bigint, bigint, bigint]
    ): [bigint, bigint, bigint, bigint] {
      return [
        (A[0] * B[0] + A[1] * B[2]) % mod,
        (A[0] * B[1] + A[1] * B[3]) % mod,
        (A[2] * B[0] + A[3] * B[2]) % mod,
        (A[2] * B[1] + A[3] * B[3]) % mod,
      ];
    }

    let p = n - 1n;
    while (p > 0n) {
      if ((p & 1n) === 1n) res = multiply(res, base);
      base = multiply(base, base);
      p >>= 1n;
    }

    return res[0];
  }
}`,
          explanation:
            "Stage 3 demonstrates **Patience Sorting LIS** running in strictly $O(N \\log N)$ time and **Matrix Exponentiation** computing $N$-th terms of linear recurrences in strictly $O(K^3 \\log N)$ time for $N = 10^{18}$.",
          timeComplexity: "LIS: O(N log N), Fibonacci: O(log N)",
          spaceComplexity: "Flat pre-allocated arrays, zero GC pressure",
        },
      ],
      stepByStep: [
        "Identify recurrence state dependencies and eliminate redundant dimensions via rolling scalar registers.",
        "For monotonic decision sequences (LIS), maintain an ordered `tails` array and update via binary search bisection (`lower_bound`).",
        "For constant-coefficient linear recurrences, transform transitions into matrix form and solve in $O(K^3 \\log N)$ via repeated squaring.",
      ],
    },
  ],
};
