import type { CoursePage } from "../../../../courseTypes";

export const page3: CoursePage = {
  id: "dsa_dp_1d_c1_p3",
  pageNumber: 3,
  title: "Microarchitecture Realities & Production Traps",
  sections: [
    {
      type: "callout",
      variant: "systems",
      title: "Register Caching in Kadane & CPU Branch Predictor Profiles",
      content:
        "High-performance compute engines optimize 1D dynamic programming for modern superscalar microarchitectures:\n\n1. **Zero-Memory Register Allocation:** In Kadane's algorithm, the loop maintains only two scalar states (`currentSum` and `maxSum`). The compiler allocates these variables directly to hardware CPU registers (`%rax` and `%rdx`), requiring zero memory loads or stores. The entire loop executes at the CPU clock frequency (1 iteration per nanosecond), auto-vectorizing across AVX-512 SIMD registers.\n2. **Branch Predictor Penalties in DP Transitions:** In DP transitions containing conditional branches (`if (dp[i-1] > 0)`), randomly alternating positive and negative values trigger branch mispredictions (15-20 cycle pipeline flushes). Modern compilers replace conditional jumps with branchless conditional moves (`cmovg`), eliminating branch penalties entirely.\n3. **Matrix Exponentiation Cache Blocking:** In linear recurrences of order $K > 32$, matrix multiplication $M \\times M$ is memory-bound. Transposing matrix $B$ before multiplication ensures sequential row-major reads across L1 cache lines, accelerating $K^3$ products by up to $8\\times$.",
    },
    {
      type: "callout",
      variant: "warning",
      title: "Production Traps, Knapsack Loop Direction & 64-Bit Integer Overflows",
      content:
        "1. **The 0/1 Knapsack Forward Loop Reuse Bug:** In 1D space-optimized 0/1 Knapsack, iterating forward from $w_i \\to W$ allows the current item to be added multiple times to the same knapsack within a single pass (silently converting it to Unbounded Knapsack). 0/1 Knapsack *must* iterate backwards from $W \\to w_i$ so each state references values from the previous item's pass.\n2. **Kadane All-Negative Array Bug:** Initializing `maxSum = 0` causes Kadane's algorithm to return 0 when all array elements are negative (e.g. `[-5, -2, -8]`), missing the true maximum sum `[-2]`. Always initialize `maxSum = nums[0]`.\n3. **64-Bit IEEE 754 Floating-Point Precision Loss:** Counting DP combinations without modulo arithmetic silently loses precision once the value exceeds $2^{53} - 1$ ($9.007 \\times 10^{15}$). Always use `BigInt` or modular arithmetic (`% 1000000007n`).\n4. **LIS Strict vs Non-Decreasing Off-by-One:** Using `lower_bound` computes strictly increasing subsequences ($a_i < a_j$), whereas `upper_bound` computes non-decreasing subsequences ($a_i \\le a_j$).",
    },
    {
      type: "callout",
      variant: "theoretical",
      title: "Algebraic Frontiers: Berlekamp-Massey & Cayley-Hamilton Optimizations",
      content:
        "Advanced algebraic DP techniques accelerate linear recurrences beyond standard matrix exponentiation:\n- **The Cayley-Hamilton Theorem:** Every square matrix $M$ satisfies its own characteristic polynomial $P(\\lambda) = \\det(\\lambda I - M) = 0$. Using polynomial division $x^N \\pmod{P(x)}$, the $N$-th power $M^N$ is computed in $O(K^2 \\log N)$ (or $O(K \\log K \\log N)$ using FFT polynomial multiplication), completely avoiding the $O(K^3)$ matrix multiplication bottleneck.\n- **The Berlekamp-Massey Algorithm (1969):** Given the first $2K$ terms of an unknown sequence generated by a linear recurrence, Berlekamp-Massey automatically finds the shortest recurrence relation in $O(K^2)$ time.",
    },
    {
      type: "prose",
      title: "1D Dynamic Programming Archetype Selection Matrix",
      content: `
| Problem Pattern | State Definition | Transition Recurrence | Time Complexity | Space Complexity |
| :--- | :--- | :--- | :--- | :--- |
| **Kadane Subarray** | Max sum ending at index $i$ | $\\text{DP}[i] = \\max(A[i], \\text{DP}[i-1] + A[i])$ | $O(N)$ | $O(1)$ (registers) |
| **Fibonacci / Robber** | Max value considering prefix $i$ | $\\text{DP}[i] = \\max(\\text{DP}[i-1], \\text{DP}[i-2] + v_i)$ | $O(N)$ | $O(1)$ (2 variables) |
| **Patience LIS** | Min tail of LIS of length $k$ | Binary search lower bound on \`tails\` | $O(N \\log N)$ | $O(N)$ (\`tails\` array) |
| **0/1 Knapsack** | Max value with capacity $w$ | Reverse loop: $\\text{DP}[w] = \\max(\\text{DP}[w], \\text{DP}[w-w_i] + v_i)$ | $O(N \\cdot W)$ | $O(W)$ (1D buffer) |
| **Unbounded Knapsack** | Max value with capacity $w$ | Forward loop: $\\text{DP}[w] = \\max(\\text{DP}[w], \\text{DP}[w-w_i] + v_i)$ | $O(N \\cdot W)$ | $O(W)$ (1D buffer) |
| **Matrix Exponentiation** | State vector $\\vec{v}_n = M^N \\vec{v}_0$ | Repeated squaring of companion matrix $M$ | $O(K^3 \\log N)$ | $O(K^2)$ (matrix) |
      `,
    },
  ],
};
