import type { CoursePage } from "../../../../courseTypes";

export const page2: CoursePage = {
  id: "dsa_dp_1d_c2_p2",
  pageNumber: 2,
  title: "Mathematical Foundations & Rigorous Invariants",
  sections: [
    {
      type: "math_proof",
      title:
        "Theorem 1: LIS Patience Sorting Correctness via Dilworth's Theorem (Aldous & Diaconis 1999)",
      theorem:
        "For any sequence of numbers $A = (a_1, a_2, \\dots, a_N)$, the number of piles $P$ generated by the greedy Patience Sorting algorithm is equal to the exact length $L$ of the Longest Increasing Subsequence (LIS) of $A$. Furthermore, patience sorting computes $L$ in strictly $O(N \\log N)$ time and $O(N)$ auxiliary space.",
      proof: `
**Proof via Poset Duality & Dilworth's Theorem:**
1. Define a partially ordered set (poset) $(A, \\prec)$ on sequence elements where:
   $$a_i \\prec a_j \\iff i < j \\quad \\text{and} \\quad a_i < a_j$$
2. In this poset:
   - A **Chain** is a sequence of elements where each element is strictly smaller and appears after the previous element—precisely an **Increasing Subsequence**.
   - An **Antichain** is a set of elements where no two elements are comparable under $\\prec$—which corresponds to a **Non-Increasing Subsequence** ($i < j \\implies a_i \\ge a_j$).
3. **Dilworth's Theorem (1950):** In any finite poset, the size of the maximum chain equals the minimum number of antichains needed to cover the poset:
   $$\\max |\\text{Chain}| = \\min |\\text{Antichain Partition}|$$
4. **Patience Sorting Mechanics:**
   - Patience sorting places each incoming card $a_k$ onto the leftmost pile whose top card is $\\ge a_k$. If no such pile exists, a new pile is created to the right.
   - Within each individual pile, cards are placed in non-increasing order from bottom to top ($a_{i_1} \\ge a_{i_2} \\ge \\dots$).
   - Therefore, each pile is a valid **Antichain** in the poset $(A, \\prec)$.
5. **Duality Equality:**
   - If patience sorting creates $P$ piles, it produces an explicit partition of $A$ into $P$ antichains.
   - When placing a card on pile $k > 1$, we can record a pointer to the current top card of pile $k - 1$ (which is strictly smaller than the incoming card).
   - Following these pointers backwards from any card on pile $P$ constructs an explicit increasing subsequence (chain) of length $P$.
   - Thus, $\\text{LIS}(A) \\ge P$.
   - By Dilworth's Theorem and the pigeonhole principle, no chain can contain more than one element from each antichain (pile), so $\\text{LIS}(A) \\le P$.
   - Hence, $\\text{LIS}(A) = P$.
6. **Complexity:** Since the top cards of the piles are always strictly increasing, finding the leftmost valid pile uses binary search ('lower_bound') in $O(\\log P) \\le O(\\log N)$ time per element, achieving total runtime $O(N \\log N)$. $\\blacksquare$
      `,
    },
    {
      type: "math_proof",
      title: "Theorem 2: Kadane's Maximum Subarray Sum Inductive Invariant",
      theorem:
        "For an array $A = (a_0, a_1, \\dots, a_{n-1})$, Kadane's recurrence $M[i] = \\max(a_i, M[i-1] + a_i)$ correctly computes the maximum contiguous subarray sum ending at index $i$, and $\\max_{0 \\le i < n} M[i]$ is the global maximum subarray sum, running in $\\Theta(n)$ time and $O(1)$ auxiliary space.",
      proof: `
**Proof by Mathematical Induction on Array Prefix Length:**
1. Let $S(i)$ denote the set of all non-empty contiguous subarrays of $A$ ending at index $i$:
   $$S(i) = \\{ (a_j, a_{j+1}, \\dots, a_i) \\mid 0 \\le j \\le i \\}$$
2. Define $M^*[i] = \\max_{B \\in S(i)} \\sum_{x \\in B} x$ as the true maximal sum of any subarray ending at $i$.
3. **Base Case ($i = 0$):**
   - $S(0) = \\{ (a_0) \\}$. The only subarray ending at 0 is $(a_0)$, with sum $a_0$.
   - $M[0] = a_0 = M^*[0]$. Base case holds.
4. **Inductive Step:** Assume $M[i-1] = M^*[i-1]$ holds for $i-1 \\ge 0$.
   - Any subarray $B \\in S(i)$ ending at $i$ either:
     - Contains only $a_i$ ($j = i$), with sum $a_i$.
     - Extends a non-empty subarray $B' \\in S(i-1)$ ($j < i$), with sum $(\\sum_{x \\in B'} x) + a_i$.
   - Maximizing over all $B \\in S(i)$:
     $$M^*[i] = \\max \\left( a_i, \\max_{B' \\in S(i-1)} \\left( \\sum_{x \\in B'} x + a_i \\right) \\right) = \\max(a_i, M^*[i-1] + a_i)$$
   - By the inductive hypothesis, $M^*[i-1] = M[i-1]$, so $M^*[i] = \\max(a_i, M[i-1] + a_i) = M[i]$.
5. The induction is complete. Since any non-empty contiguous subarray of $A$ must end at some index $i \\in \\{0, \\dots, n-1\\}$, the global maximum subarray sum is $\\max_{0 \\le i < n} M[i]$.
6. The state $M[i]$ depends only on $M[i-1]$, allowing memory compression to a single scalar variable in $O(1)$ space. $\\blacksquare$
      `,
    },
  ],
};
