import type { CoursePage } from "../../../../courseTypes";

export const page1: CoursePage = {
  id: "ml_speculative_decoding_c1_p1",
  pageNumber: 1,
  title: "Speculative Decoding: Rejection Sampling & Parallel Verification",
  sections: [
    {
      type: "callout",
      variant: "systems",
      title: "The Physical Crisis: Memory-Bound Arithmetic Stalls in Large Models",
      content:
        "Large Language Models during single-token autoregressive decoding are fundamentally bottlenecked by GPU High Bandwidth Memory (HBM) bandwidth rather than compute. To generate a single token from a 70B parameter model (140 GB in FP16), the GPU must stream all 140 GB of weights from HBM across the memory bus to perform only $2 \\times 70 \\times 10^9$ FLOPs. On an NVIDIA H100 (3.35 TB/s HBM bandwidth), this limits generation latency to $T_{\\text{step}} \\approx \\frac{140 \\text{ GB}}{3.35 \\text{ TB/s}} \\approx 41.8 \\text{ ms/token}$ (~24 tokens/sec). The Tensor Cores sit idle for over 90% of each cycle. Speculative Decoding (Leviathan et al., 2023; Chen et al., 2023) breaks this physical bottleneck by transforming memory-bound token generation into compute-dense parallel verification.",
    },
    {
      type: "mental_model",
      title: "Mental Model: Speculate Rapidly, Verify Concurrently",
      visualIntuition:
        "1. Small Draft Model (8B): Rapidly speculates gamma = 4 candidate tokens [x_1, x_2, x_3, x_4] in 4 fast steps.\\n2. Large Target Model (70B): Evaluates all 4 candidate tokens in a SINGLE parallel forward pass of length gamma+1 = 5.\\n3. Modified Rejection Sampling: Evaluates acceptance probabilities min(1, p(x_i)/q(x_i)).\\n   - Accepted x_1, x_2 -> Rejected x_3 -> Resample x_3 from residual distribution p'(x) -> Discard x_4.\\n4. Result: 3 target-quality tokens produced in the time of 1 target forward pass!",
      invariant:
        "Exact Distribution Equivalence Invariant: The probability distribution of tokens generated by speculative decoding is mathematically identical to sampling directly from the Target model p(x): P_{spec}(X = x) = p(x) for all x in Vocabulary.",
      stateTransitions:
        "Draft Phase (generate gamma tokens from small model q) -> Target Verification Phase (compute target logits p for all gamma positions simultaneously) -> Rejection Sampling Loop (accept/reject sequentially) -> KV Cache Rollback (rewind KV pointers for rejected tokens) -> Emit accepted tokens + bonus token.",
      naiveBottleneck:
        "Generating tokens sequentially from the target model requires loading 140 GB of weights once for every single token generated.",
      optimalInsight:
        "Target model parallel verification processes gamma+1 tokens in the same latency as 1 token (converting GEMV to GEMM), yielding 2x-3.5x wall-clock speedup with zero degradation in generation accuracy.",
    },
    {
      type: "math_proof",
      title: "Mathematical Proof: Exact Target Distribution Invariance",
      theorem:
        "Let $p(x)$ be the Target model probability distribution and $q(x)$ be the Draft model distribution over vocabulary $\\mathcal{V}$. Speculative sampling accepts a draft token $x \\sim q$ with probability $\\min\\left(1, \\frac{p(x)}{q(x)}\\right)$. If rejected, it resamples a replacement token from the residual distribution $p'(x) = \\frac{\\max(0, p(x) - q(x))}{1 - \\beta}$, where $\\beta = \\sum_{v \\in \\mathcal{V}} \\min(p(v), q(v))$ is the total acceptance probability. The output distribution of this process equals $p(x)$ identically.",
      proof:
        "1. Probability of Emitting Token $x$ via Acceptance:\\nToken $x$ is drafted with probability $q(x)$ and accepted with probability $\\min\\left(1, \\frac{p(x)}{q(x)}\\right)$. Thus:\\n$$\\mathbb{P}(\\text{emit } x \\text{ via acceptance}) = q(x) \\cdot \\min\\left(1, \\frac{p(x)}{q(x)}\\right) = \\min(q(x), p(x))$$\\n\\n2. Total Rejection Probability:\\nThe total probability of rejecting the drafted token is:\\n$$\\mathbb{P}(\\text{rejection}) = 1 - \\sum_{v \\in \\mathcal{V}} \\min(q(v), p(v)) = 1 - \\beta$$\\n\\n3. Probability of Emitting Token $x$ via Rejection Resampling:\\nUpon rejection, token $x$ is drawn from the adjusted residual distribution $p'(x)$:\\n$$\\begin{aligned} \\mathbb{P}(\\text{emit } x \\text{ via resampling}) &= \\mathbb{P}(\\text{rejection}) \\cdot p'(x) \\\\ &= (1 - \\beta) \\cdot \\frac{\\max(0, p(x) - q(x))}{1 - \\beta} \\\\ &= \\max(0, p(x) - q(x)) \\end{aligned}$$\\n\\n4. Total Probability of Emitting Token $x$:\\nSumming both mutually exclusive emission pathways:\\n$$\\begin{aligned} \\mathbb{P}(X = x) &= \\mathbb{P}(\\text{acceptance}) + \\mathbb{P}(\\text{resampling}) \\\\ &= \\min(p(x), q(x)) + \\max(0, p(x) - q(x)) \\end{aligned}$$\\n- If $p(x) \\ge q(x)$: $\\min(p(x), q(x)) + (p(x) - q(x)) = q(x) + p(x) - q(x) = p(x)$.\\n- If $p(x) < q(x)$: $\\min(p(x), q(x)) + 0 = p(x)$.\\n\\nIn all cases, $\\mathbb{P}(X = x) = p(x)$ identically. This rigorously proves that speculative decoding preserves target model output distribution perfectly.",
    },
  ],
};
