export { CertificateVerificationModal } from "./CertificateVerificationModal";
export type { CertificateVerificationModalProps } from "./CertificateVerificationModal";

export { CoursePlayerStage } from "./CoursePlayerStage";
export type { CoursePlayerStageProps } from "./CoursePlayerStage";

export { FlashcardReviewModal } from "./FlashcardReviewModal";
export type { FlashcardReviewModalProps, SpacedRepetitionRating } from "./FlashcardReviewModal";

export { NumericalLabPlayground } from "./NumericalLabPlayground";
export type { NumericalLabPlaygroundProps } from "./NumericalLabPlayground";
export { renderFormattedMath, renderRichProblemText, TOPIC_PRESETS } from "./numericalLabUtils";
export type { NumericalAttemptRecord } from "./numericalLabUtils";

export { TimeTravelStepControls } from "./TimeTravelStepControls";
export type { TimeTravelStepControlsProps } from "./TimeTravelStepControls";

export {
  InteractiveCodingCheckpointView,
  categorizeTestCase,
  formatDataForDisplay,
} from "./InteractiveCodingCheckpointView";
export type {
  InteractiveCodingCheckpointViewProps,
  TestCaseCategory,
} from "./InteractiveCodingCheckpointView";

export { AdversarialStressArena } from "./AdversarialStressArena";
export type { AdversarialStressArenaProps } from "./AdversarialStressArena";

export {
  AlgorithmRaceComparator,
  RACE_MATCHUP_PRESETS,
  SCALE_POINTS,
  getRaceMatchupPreset,
  computeRaceTelemetry,
  calculateWinnerPodium,
  simulateRaceStep,
  generateCompetitorDataPoints,
  formatBytes,
  formatLatency,
  formatOpsPerSec,
} from "./AlgorithmRaceComparator";
export type {
  AlgorithmRaceComparatorProps,
  AlgorithmCompetitor,
  CompetitorColorTheme,
  CompetitorTelemetry,
  MatchupId,
  RaceMatchupPreset,
  RaceSimulationState,
  ScalePoint,
  WinnerPodiumResult,
} from "./AlgorithmRaceComparator";

export {
  GraphNetworkFlowStudio,
  NETWORK_FLOW_PRESETS,
  FLOW_ALGORITHMS,
  edgeKey,
  computeResidualCapacityMap,
  computeResidualGraph,
  computeLevelGraphBFS,
  computeMinCutPartition,
  computeFlowTelemetry,
  verifyFlowConservation,
  verifyCapacityConstraints,
  solveEdmondsKarp,
  solveDinic,
  solvePushRelabel,
  solveMinCostMaxFlow,
  executeFlowAlgorithm,
  formatFlow,
  formatCost,
  runEdmondsKarpAlgorithm,
  runDinicAlgorithm,
  runPushRelabelAlgorithm,
  runBellmanFordDijkstra,
} from "../primitives/GraphNetworkFlowStudio";
export type {
  GraphNetworkFlowStudioProps,
  FlowAlgorithmMode,
  FlowAlgorithmId,
  NetworkFlowPresetId,
  FlowPresetId,
  EdgeLabelDisplayMode,
  FlowStudioViewMode,
  NetworkFlowNode,
  FlowNode,
  NetworkFlowEdge,
  FlowEdge,
  FlowGraph,
  ResidualEdge,
  AugmentingStep,
  MinCutPartition,
  MinCutPartitionResult,
  PushRelabelNodeState,
  FlowTelemetry,
  FlowStepTrace,
  NetworkFlowPreset,
  FlowPresetConfig,
  FlowConservationStatus,
  FlowComputationResult,
  AlgorithmSimulationResult,
  ShortestPathSimulationResult,
  FlowAlgorithmSpec,
} from "../primitives/GraphNetworkFlowStudio";

export {
  DPTreeDecompositionStudio,
  DP_TREE_MODALITIES,
  DP_TREE_PRESETS,
  TREE_DIAMETER_PRESETS,
  HLD_PRESETS,
  LCA_PRESETS,
  CHT_PRESETS,
  buildTreeFromEdges,
  computeTwoDFS,
  computeTreeDiameterDP,
  computeHLD,
  queryHLDPath,
  buildBinaryLiftingTable,
  queryLCA,
  computeLineIntersection,
  buildConvexHullTrick,
  queryCHT,
  computeTreeLayout,
} from "../primitives/DPTreeDecompositionStudio";
export type {
  DPTreeStudioModality,
  TreeNode,
  TreeEdge,
  TreeGraph,
  TreeDiameterDPResult,
  TwoDFSResult,
  HLDResult,
  HLDPathInterval,
  HLDPathQueryResult,
  BinaryLiftingTable,
  LCAJumpStep,
  LCASimultaneousJumpStep,
  LCAQueryResult,
  CHTLine,
  CHTIntersection,
  CHTPoppedLine,
  CHTHistoryStep,
  CHTEnvelopeResult,
  CHTLineEvaluation,
  CHTQueryResult,
  DPTreeDecompositionStudioProps,
  DPTreePresetConfig,
} from "../primitives/DPTreeDecompositionStudio";

export {
  ComputationalGeometrySweepStudio,
  crossProduct2D,
  turnOrientation,
  euclideanDistance,
  euclideanDistanceSquared,
  shoelacePolygonArea,
  polygonPerimeter,
  computeMonotoneChain,
  computeGrahamScan,
  computeQuickHull,
  lineSegmentIntersection,
  computeBentleyOttmann,
  computeClosestPairBruteForce,
  computeClosestPairDC,
  isPointOnSegment,
  computeRayCastingPIP,
  computeWindingNumberPIP,
  GEOMETRY_MODALITIES,
  CONVEX_HULL_PRESETS,
  BENTLEY_OTTMANN_PRESETS,
  CLOSEST_PAIR_PRESETS,
  POINT_IN_POLYGON_PRESETS,
  GEOMETRY_STUDIO_PRESETS,
} from "../primitives/ComputationalGeometrySweepStudio";
export type {
  GeometryStudioModality,
  ConvexHullAlgorithmId,
  Point2D,
  LineSegment,
  TurnOrientation,
  ConvexHullStep,
  ConvexHullAlgorithmResult,
  BentleyOttmannEventType,
  SweepEvent,
  IntersectionPoint,
  BentleyOttmannStep,
  BentleyOttmannResult,
  ClosestPairCandidate,
  ClosestPairStep,
  ClosestPairDCResult,
  ClosestPairResult,
  RayCastingEdgeTrace,
  PIPStepTrace,
  RayCastingPIPResult,
  WindingNumberEdgeTrace,
  WindingNumberPIPResult,
  GeometryStudioPreset,
  ComputationalGeometrySweepStudioProps,
} from "../primitives/ComputationalGeometrySweepStudio";

export {
  SuffixAutomataStudio,
  buildSuffixAutomaton,
  buildSuffixAutomatonStepByStep,
  buildSuffixArray,
  computeKasaiLCP,
  queryLCPInterval,
  countDistinctSubstringsSAM,
  computeDAGSubstringsDP,
  findKthSubstring,
  searchPatternSAM,
  computeEndposOccurrences,
  layoutSAMGraph,
  SAM_STUDIO_PRESETS,
} from "../primitives";
export type {
  SAMStudioModality,
  SAMPresetId,
  SAMState,
  SuffixAutomaton,
  SAMConstructionPhase,
  SAMStepTrace,
  SuffixArrayResult,
  KasaiStepTrace,
  KasaiLCPResult,
  LCPQueryResult,
  DAGSubstringsDPResult,
  KthSubstringResult,
  SAMPatternSearchResult,
  EndposPropagationResult,
  SAMGraphNode,
  SAMGraphEdge,
  SAMGraphLayout,
  SAMPreset,
  SuffixAutomataStudioProps,
} from "../primitives";

export {
  SpatialIndexBVHStudio,
  SPATIAL_EPSILON,
  euclideanDistance2D,
  euclideanDistanceSquared2D,
  aabbUnion,
  aabbFromPoints,
  aabbArea,
  aabbHalfArea,
  aabbIntersection,
  aabbIntersectBox,
  pointToAABBDistanceMin,
  pointToAABBDistanceMax,
  rayAABBIntersect,
  rayCircleIntersect,
  raySegmentIntersect,
  rayPrimitiveIntersect,
  buildKDTree2D,
  collectKDTreeLines,
  generateKDSplitSteps,
  getKDTreeDepth,
  countKDTreeNodes,
  findKNearestNeighbors,
  generateKNNSteps,
  pickSeeds,
  pickNext,
  quadraticSplit,
  buildRTree2D,
  queryRTreeRange,
  generateRTreeRangeQuerySteps,
  computeSAHCost,
  buildBVHWithSAH,
  traverseBVHRay,
  generateBVHRaySteps,
  SPATIAL_INDEX_MODALITIES,
  KD_TREE_PRESETS,
  KNN_QUERY_PRESETS,
  RTREE_PRESETS,
  BVH_SAH_PRESETS,
  SPATIAL_INDEX_PRESETS,
} from "../primitives";
export type {
  SpatialModality,
  SpatialPoint2D,
  SpatialAABB,
  Ray2D,
  KDTreeAxis,
  KDSplitLine,
  KDTreeNode,
  KDSplitStep,
  NeighborCandidate,
  KNNStepTrace,
  KNNResult,
  RTreeEntry,
  RTreeNode,
  RTreeRangeStepTrace,
  RTreeRangeResult,
  BVHPrimitiveType,
  BVHPrimitive,
  BVHNode,
  BVHBuildOptions,
  RayHit,
  BVHRayStepTrace,
  BVHRayResult,
  SpatialStudioPreset,
  SpatialModalityInfo,
  SpatialIndexBVHStudioProps,
} from "../primitives";

export {
  AhoCorasickAutomataStudio,
  GraphCanvasView as ACGraphCanvasView,
  AHO_CORASICK_PRESETS,
  AHO_CORASICK_MODALITY_CONFIGS,
  cloneACTrie,
  createEmptyACTrie,
  validateACPatterns,
  getNodePrefixPath as getACNodePrefixPath,
  buildACTrie,
  generateTrieBuildTrace,
  computeFailureLinks,
  generateFailureLinksTrace,
  computeDictSuffixLinks,
  collectChainOutputs as collectACChainOutputs,
  generateDictSuffixLinksTrace,
  buildFullAhoCorasick,
  computeDFATransitionMatrix,
  searchAhoCorasickStudio,
  searchACTrie,
  searchAhoCorasickACTrie,
  naiveMultiPatternSearch,
  generateStreamingSearchTrace,
  layoutACTrie,
} from "../primitives";
export type {
  AhoCorasickModality,
  ACPresetId,
  ACTrieNode,
  ACTrie,
  ACMatchOccurrence,
  ACTransitionMatrix,
  ACTrieBuildAction,
  ACTrieBuildStep,
  ACFailLinkPhase,
  ACFailLinkBuildStep,
  ACDictLinkPhase,
  ACDictLinkBuildStep,
  ACSearchTransitionType,
  ACSearchStep,
  ACLayoutNode,
  ACLayoutEdge,
  ACLayoutResult,
  ACPreset,
  AhoCorasickAutomataStudioProps,
} from "../primitives";

export {
  TarjanSCC2SATStudio,
  SCC_PALETTE,
  TARJAN_MODALITY_CONFIGS,
  TARJAN_2SAT_PRESETS,
  runTarjanSCC,
  findBridgesAndArticulationPoints,
  buildCondensationGraph,
  parse2SATFormula,
  build2SATImplicationGraph,
  solve2SAT,
  evaluate2SATFormula,
  generateTarjanSteps,
  negate2SATLiteral,
  format2SATLiteral,
  format2SATClause,
  format2SATFormula,
} from "../primitives";
export type {
  TarjanStudioModality,
  TarjanPresetId,
  TarjanGraphNode,
  TarjanGraphEdge,
  TarjanGraph,
  TarjanSCCResult,
  BridgeEdgeInfo,
  BridgesArticulationResult,
  CondensationNode,
  CondensationEdge,
  CondensationGraphResult,
  TwoSATLiteral,
  TwoSATClause,
  TwoSATFormula,
  TwoSATImplicationEdge,
  TwoSATImplicationGraph,
  TwoSATContradiction,
  TwoSATClauseEvaluation,
  TwoSATSolverResult,
  TarjanStepAction,
  TarjanTelemetry,
  TarjanAnimationStep,
  TarjanPreset,
  TarjanModalityConfig,
  TarjanSCC2SATStudioProps,
} from "../primitives";

export {
  TreapSplayTreeStudio,
  TREAP_SPLAY_PRESETS,
  generateUniqueNodeId,
  getCartesianSize,
  createCartesianNode,
  updateCartesianSize,
  cloneCartesianTree,
  splitCartesian,
  mergeCartesian,
  insertCartesian,
  deleteCartesian,
  findCartesian,
  kthCartesian,
  collectCartesianInOrder,
  computeCartesianHeight,
  validateCartesianTreap,
  getImplicitSize,
  createImplicitNode,
  pushDownImplicit,
  updateImplicitSize,
  splitImplicit,
  mergeImplicit,
  reverseRangeImplicit,
  cyclicShiftImplicit,
  insertAtImplicit,
  deleteAtImplicit,
  extractImplicitArray,
  computeImplicitHeight,
  validateImplicitTreap,
  getSplaySize,
  createSplayNode,
  updateSplaySize,
  rotateRightSplay,
  rotateLeftSplay,
  calculateSplayPotentialPhi,
  computeSplayHeight,
  splayTree,
  insertSplay,
  deleteSplay,
  validateSplayTree,
  createLCTNode,
  createEmptyLCTForest,
  cloneLCTForest,
  isLCTAuxRoot,
  pushDownLCTNode,
  updateLCTNodeSize,
  pushDownLCTPath,
  rotateLCT,
  splayLCT,
  accessLCT,
  makeRootLCT,
  findRootLCT,
  linkLCT,
  cutLCT,
  getLCTPreferredEdges,
  getLCTPathParentEdges,
  generateCartesianOperationSteps,
  generateImplicitOperationSteps,
  generateSplayOperationSteps,
  generateLCTOperationSteps,
  layoutBinaryTree,
  layoutLCTForest,
} from "../primitives";
export type {
  TreapSplayModality,
  TreapSplayPresetId,
  CartesianNode,
  ImplicitNode,
  SplayNode,
  SplayRotationType,
  LCTNode,
  LCTForest,
  TreapSplayTelemetry,
  TreapSplayAnimationStep,
  TreapSplayPreset,
  RenderNodeLayout,
  RenderEdgeLayout,
  SplayStepLog,
  TreapSplayTreeStudioProps,
} from "../primitives";

export {
  BipartiteMatchingStudio,
  MATCHING_MODALITY_INFOS,
  BIPARTITE_MATCHING_PRESETS,
  runHopcroftKarpAlgorithm,
  runKonigDuality,
  runHungarianAlgorithm,
  runHallConditionScanner,
} from "../primitives";
export type {
  BipartiteStudioModality,
  BipartitePresetId,
  BipartiteNode,
  BipartiteEdge,
  BipartiteGraph,
  BipartiteStepAction,
  BipartiteTelemetry,
  BipartiteAnimationStep,
  BipartiteModalityConfig,
  BipartiteMatchingStudioProps,
} from "../primitives";

export {
  VoronoiDelaunayStudio,
  VORONOI_DEFAULT_CANVAS_WIDTH,
  VORONOI_DEFAULT_CANVAS_HEIGHT,
  VORONOI_DEFAULT_BOUNDS,
  VORONOI_PASTEL_PALETTE,
  VORONOI_MODALITIES,
  VORONOI_STUDIO_PRESETS,
  voronoiDistance,
  voronoiDistanceSq,
  voronoiCrossProduct2D,
  isCCWVoronoi,
  voronoiTurnOrientation,
  computeCircumcircle,
  inCircumcircleDeterminant,
  inCircumcircle,
  clipPolygonWithBisector,
  computePolygonAreaAndCentroid,
  computeBowyerWatsonDelaunay,
  computeVoronoiDiagramFromDelaunay,
  computeLloydRelaxation,
  computeFortuneSweep,
  DisjointSetUnion,
  computeEMST,
  computeBruteForceMST,
  computeVoronoiStudioTelemetry,
} from "../primitives";
export type {
  VoronoiStudioModality,
  VoronoiPresetId,
  VoronoiPoint2D,
  VoronoiBoundingBox,
  VoronoiCircumcircle,
  VoronoiTriangle2D,
  DelaunayEdge,
  VoronoiEdge,
  VoronoiCell,
  BowyerWatsonAction,
  BowyerWatsonStep,
  BowyerWatsonResult,
  FortuneEventType,
  VoronoiSiteEvent,
  VoronoiCircleEvent,
  VoronoiFortuneEvent,
  BeachlineArc,
  FortuneSweepStep,
  EMSTEdgeStatus,
  EMSTEdge,
  EMSTStep,
  EMSTResult,
  VoronoiPreset,
  VoronoiStudioTelemetry,
  VoronoiModalityConfig,
  VoronoiDelaunayStudioProps,
} from "../primitives";
