/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MlInfraRouteImport } from './routes/ml-infra'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as TriviaRouteImport } from './routes/trivia'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceAlgorithmIdRouteImport } from './routes/workspace.$algorithmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MlInfraRoute = MlInfraRouteImport.update({
  id: '/ml-infra',
  path: '/ml-infra',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const TriviaRoute = TriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAlgorithmIdRoute = WorkspaceAlgorithmIdRouteImport.update({
  id: '/workspace/$algorithmId',
  path: '/workspace/$algorithmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ml-infra': typeof MlInfraRoute
  '/problems': typeof ProblemsRoute
  '/trivia': typeof TriviaRoute
  '/learn': typeof LearnRoute
  '/workspace/$algorithmId': typeof WorkspaceAlgorithmIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ml-infra': typeof MlInfraRoute
  '/problems': typeof ProblemsRoute
  '/trivia': typeof TriviaRoute
  '/learn': typeof LearnRoute
  '/workspace/$algorithmId': typeof WorkspaceAlgorithmIdRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ml-infra': typeof MlInfraRoute
  '/problems': typeof ProblemsRoute
  '/trivia': typeof TriviaRoute
  '/learn': typeof LearnRoute
  '/workspace/$algorithmId': typeof WorkspaceAlgorithmIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ml-infra'
    | '/problems'
    | '/trivia'
    | '/learn'
    | '/workspace/$algorithmId'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ml-infra'
    | '/problems'
    | '/trivia'
    | '/learn'
    | '/workspace/$algorithmId'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/ml-infra'
    | '/problems'
    | '/trivia'
    | '/learn'
    | '/workspace/$algorithmId'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MlInfraRoute: typeof MlInfraRoute
  ProblemsRoute: typeof ProblemsRoute
  TriviaRoute: typeof TriviaRoute
  LearnRoute: typeof LearnRoute
  WorkspaceAlgorithmIdRoute: typeof WorkspaceAlgorithmIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-infra': {
      id: '/ml-infra'
      path: '/ml-infra'
      fullPath: '/ml-infra'
      preLoaderRoute: typeof MlInfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trivia': {
      id: '/trivia'
      path: '/trivia'
      fullPath: '/trivia'
      preLoaderRoute: typeof TriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$algorithmId': {
      id: '/workspace/$algorithmId'
      path: '/workspace/$algorithmId'
      fullPath: '/workspace/$algorithmId'
      preLoaderRoute: typeof WorkspaceAlgorithmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MlInfraRoute: MlInfraRoute,
  ProblemsRoute: ProblemsRoute,
  TriviaRoute: TriviaRoute,
  LearnRoute: LearnRoute,
  WorkspaceAlgorithmIdRoute: WorkspaceAlgorithmIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
