import { indexPlacements } from "../../curriculum/trees";
import type { MLInfraCurriculumPlacement } from "./data/mlInfraTypes";

export {
  ML_INFRA_FAMILIES,
  mlInfraFamilyColor,
  mlInfraFamilyFill,
  mlInfraFamilyFillHover,
  mlInfraFamilyLabel,
} from "./data/mlInfraTypes";
export type {
  MLInfraCurriculumPlacement,
  MLInfraFamily,
  MLInfraFamilyId,
} from "./data/mlInfraTypes";

export const ML_INFRA_TREE_PLACEMENTS: readonly MLInfraCurriculumPlacement[] = [
  {
    id: "ml_matrix_memory_layout",
    topicId: "ml_matrix_memory_layout",
    title: "Matrix Memory Layout & Flat Offsets",
    description: "Contiguous memory, strides, offsets, and row/column-major layouts.",
    family: "linear-algebra",
    difficulty: "Easy",
    prerequisites: [],
    x: 550,
    y: 200,
  },
  {
    id: "ml_tensor_strides_views",
    topicId: "ml_tensor_strides_views",
    title: "Tensor Strides, Views & Broadcasting",
    description: "Implicit broadcasting, memory coalescing, and non-copy tensor views.",
    family: "linear-algebra",
    difficulty: "Easy",
    prerequisites: ["ml_matrix_memory_layout"],
    x: 850,
    y: 200,
  },
  {
    id: "ml_vector_spaces_gram_schmidt",
    topicId: "ml_vector_spaces_gram_schmidt",
    title: "Vector Spaces, Orthogonality & Gram-Schmidt",
    description: "Vector projections, modified Gram-Schmidt, and numerical stability.",
    family: "linear-algebra",
    difficulty: "Medium",
    prerequisites: ["ml_tensor_strides_views"],
    x: 1150,
    y: 200,
  },
  {
    id: "ml_matrix_svd_pca",
    topicId: "ml_matrix_svd_pca",
    title: "Matrix Decompositions, SVD & PCA",
    description: "Eigendecomposition, power iteration, and dimensionality reduction.",
    family: "linear-algebra",
    difficulty: "Hard",
    prerequisites: ["ml_vector_spaces_gram_schmidt"],
    x: 1450,
    y: 200,
  },
  {
    id: "ml_gradients_jacobians_hessians",
    topicId: "ml_gradients_jacobians_hessians",
    title: "Gradients, Jacobians & Hessians",
    description: "Finite differences, numerical Jacobians, and catastrophic cancellation.",
    family: "calculus-autograd",
    difficulty: "Medium",
    prerequisites: ["ml_tensor_strides_views"],
    x: 550,
    y: 500,
  },
  {
    id: "ml_autodiff_engines",
    topicId: "ml_autodiff_engines",
    title: "Automatic Differentiation Engines",
    description: "Reverse-mode autodiff, dynamic computation graphs, and topological sort.",
    family: "calculus-autograd",
    difficulty: "Hard",
    prerequisites: ["ml_gradients_jacobians_hessians"],
    x: 850,
    y: 500,
  },
  {
    id: "ml_gradient_descent_adamw",
    topicId: "ml_gradient_descent_adamw",
    title: "Gradient Descent & AdamW Optimizer",
    description: "Momentum, decoupled weight decay, and bias-corrected moving averages.",
    family: "calculus-autograd",
    difficulty: "Medium",
    prerequisites: ["ml_autodiff_engines"],
    x: 1150,
    y: 500,
  },
  {
    id: "ml_loss_functions_info_theory",
    topicId: "ml_loss_functions_info_theory",
    title: "Loss Functions & Information Theory",
    description: "Stable cross-entropy, log-sum-exp trick, and overflow prevention.",
    family: "calculus-autograd",
    difficulty: "Medium",
    prerequisites: ["ml_autodiff_engines"],
    x: 1450,
    y: 500,
  },
  {
    id: "ml_distributions_covariance",
    topicId: "ml_distributions_covariance",
    title: "Probability Distributions & Covariance",
    description: "Random variables, expectation, variance, and sample covariance matrices.",
    family: "probability-stats",
    difficulty: "Easy",
    prerequisites: [],
    x: 1750,
    y: 200,
  },
  {
    id: "ml_mle_map_naive_bayes",
    topicId: "ml_mle_map_naive_bayes",
    title: "MLE, MAP & Naive Bayes",
    description: "Bayes' theorem, log probabilities, and Laplace smoothing.",
    family: "probability-stats",
    difficulty: "Medium",
    prerequisites: ["ml_distributions_covariance"],
    x: 2050,
    y: 200,
  },
  {
    id: "ml_hypothesis_testing_bootstrap",
    topicId: "ml_hypothesis_testing_bootstrap",
    title: "Hypothesis Testing & Bootstrap A/B Testing",
    description: "Confidence intervals, reservoir sampling, and stochastic resampling.",
    family: "probability-stats",
    difficulty: "Medium",
    prerequisites: ["ml_distributions_covariance"],
    x: 2350,
    y: 200,
  },
  {
    id: "ml_sampling_top_p",
    topicId: "ml_sampling_top_p",
    title: "Sampling Algorithms & Top-P Nucleus Sampling",
    description: "Temperature scaling, Top-P/Top-K truncation, and distribution entropy.",
    family: "probability-stats",
    difficulty: "Hard",
    prerequisites: ["ml_hypothesis_testing_bootstrap"],
    x: 2650,
    y: 200,
  },
  {
    id: "ml_linear_logistic_regression",
    topicId: "ml_linear_logistic_regression",
    title: "Linear & Logistic Regression",
    description: "Gradient descent for binary classification and convex optimization.",
    family: "classical-ml",
    difficulty: "Easy",
    prerequisites: ["ml_distributions_covariance", "ml_gradients_jacobians_hessians"],
    x: 1800,
    y: 800,
  },
  {
    id: "ml_decision_trees_cart",
    topicId: "ml_decision_trees_cart",
    title: "Decision Trees & Gini Impurity Split",
    description: "Information gain, recursive splitting, and memory-efficient tree building.",
    family: "classical-ml",
    difficulty: "Medium",
    prerequisites: ["ml_linear_logistic_regression"],
    x: 2100,
    y: 800,
  },
  {
    id: "ml_ensemble_xgboost",
    topicId: "ml_ensemble_xgboost",
    title: "Random Forest & XGBoost Split Gain",
    description: "Bagging, boosting, out-of-bag error, and gradient boosted trees.",
    family: "classical-ml",
    difficulty: "Hard",
    prerequisites: ["ml_decision_trees_cart"],
    x: 2400,
    y: 800,
  },
  {
    id: "ml_clustering_kmeans_dbscan",
    topicId: "ml_clustering_kmeans_dbscan",
    title: "Clustering: K-Means++ & DBSCAN",
    description: "Centroid initialization, density-based clustering, and distance metrics.",
    family: "classical-ml",
    difficulty: "Medium",
    prerequisites: ["ml_decision_trees_cart"],
    x: 2700,
    y: 800,
  },
  {
    id: "ml_svm_kernel_smo",
    topicId: "ml_svm_kernel_smo",
    title: "Support Vector Machines & Kernel Tricks",
    description: "Max-margin classifiers, kernel methods, and support vector identification.",
    family: "classical-ml",
    difficulty: "Hard",
    prerequisites: ["ml_linear_logistic_regression"],
    x: 3000,
    y: 800,
  },
  {
    id: "ml_collaborative_filtering_als",
    topicId: "ml_collaborative_filtering_als",
    title: "Matrix Factorization & Alternating Least Squares",
    description: "Recommender systems, user-item embeddings, and implicit feedback.",
    family: "classical-ml",
    difficulty: "Hard",
    prerequisites: ["ml_linear_logistic_regression", "ml_matrix_svd_pca"],
    x: 3300,
    y: 800,
  },
  {
    id: "ml_mlp_backpropagation",
    topicId: "ml_mlp_backpropagation",
    title: "Multilayer Perceptrons & Backpropagation",
    description: "Dense layers, forward passes, and gradient flow through deep networks.",
    family: "deep-learning",
    difficulty: "Medium",
    prerequisites: ["ml_autodiff_engines"],
    x: 300,
    y: 800,
  },
  {
    id: "ml_activations_online_softmax",
    topicId: "ml_activations_online_softmax",
    title: "Activations, GELU, SwiGLU & Online Softmax",
    description: "Non-linearities, online safe softmax, and activation memory footprints.",
    family: "deep-learning",
    difficulty: "Medium",
    prerequisites: ["ml_mlp_backpropagation", "ml_loss_functions_info_theory"],
    x: 600,
    y: 800,
  },
  {
    id: "ml_normalization_rmsnorm",
    topicId: "ml_normalization_rmsnorm",
    title: "LayerNorm, BatchNorm & RMSNorm",
    description:
      "Internal covariate shift, running statistics, and root mean square normalization.",
    family: "deep-learning",
    difficulty: "Medium",
    prerequisites: ["ml_activations_online_softmax"],
    x: 900,
    y: 800,
  },
  {
    id: "ml_convolutions_im2col_gemm",
    topicId: "ml_convolutions_im2col_gemm",
    title: "Spatial Convolutions & Im2Col GEMM",
    description:
      "Receptive fields, padding semantics, and lowering convolutions to matrix multiplication.",
    family: "deep-learning",
    difficulty: "Hard",
    prerequisites: ["ml_normalization_rmsnorm"],
    x: 1200,
    y: 800,
  },
  {
    id: "ml_recurrent_lstm_gru",
    topicId: "ml_recurrent_lstm_gru",
    title: "Recurrent Networks & LSTM/GRU Gating",
    description: "Hidden states, gating mechanisms, and mitigating vanishing gradients in BPTT.",
    family: "deep-learning",
    difficulty: "Hard",
    prerequisites: ["ml_normalization_rmsnorm"],
    x: 1500,
    y: 800,
  },
  {
    id: "ml_trie_aho_corasick",
    topicId: "ml_trie_aho_corasick",
    title: "Trie Vocabularies & Aho-Corasick",
    description: "Prefix trees, string matching, and efficient vocabulary representation.",
    family: "tokenization-retrieval",
    difficulty: "Medium",
    prerequisites: ["ml_tensor_strides_views"],
    x: 1750,
    y: 500,
  },
  {
    id: "ml_subword_bpe_tiktoken",
    topicId: "ml_subword_bpe_tiktoken",
    title: "Subword Tokenization: BPE & Tiktoken",
    description: "Byte pair encoding, subword segmentation, and out-of-vocabulary handling.",
    family: "tokenization-retrieval",
    difficulty: "Medium",
    prerequisites: ["ml_trie_aho_corasick"],
    x: 2050,
    y: 500,
  },
  {
    id: "ml_kd_trees_top_k",
    topicId: "ml_kd_trees_top_k",
    title: "Exact Top-K Retrieval & K-D Trees",
    description: "Spatial partitioning, nearest neighbors, and multi-dimensional search.",
    family: "tokenization-retrieval",
    difficulty: "Hard",
    prerequisites: ["ml_subword_bpe_tiktoken"],
    x: 2350,
    y: 500,
  },
  {
    id: "ml_ann_hnsw_ivfpq",
    topicId: "ml_ann_hnsw_ivfpq",
    title: "Approximate Nearest Neighbors: HNSW & IVF-PQ",
    description:
      "Hierarchical navigable small worlds, inverted file indexes, and product quantization.",
    family: "tokenization-retrieval",
    difficulty: "Hard",
    prerequisites: ["ml_kd_trees_top_k"],
    x: 2650,
    y: 500,
  },
  {
    id: "ml_attention_causal_sdpa",
    topicId: "ml_attention_causal_sdpa",
    title: "Scaled Dot-Product Attention & Causal Masking",
    description: "Query-Key-Value interactions, attention scores, and autoregressive masking.",
    family: "transformers",
    difficulty: "Hard",
    prerequisites: ["ml_recurrent_lstm_gru", "ml_subword_bpe_tiktoken"],
    x: 1200,
    y: 1100,
  },
  {
    id: "ml_rope_gqa_attention",
    topicId: "ml_rope_gqa_attention",
    title: "Multi-Head, GQA & Rotary Position Encodings (RoPE)",
    description: "Grouped-query attention, relative positional embeddings, and KV head sharing.",
    family: "transformers",
    difficulty: "Hard",
    prerequisites: ["ml_attention_causal_sdpa"],
    x: 1600,
    y: 1100,
  },
  {
    id: "ml_flashattention_sram_tiling",
    topicId: "ml_flashattention_sram_tiling",
    title: "IO-Aware FlashAttention SRAM Tiling",
    description: "Memory-bound operations, SRAM tiling, and avoiding HBM read/write overhead.",
    family: "transformers",
    difficulty: "Hard",
    prerequisites: ["ml_rope_gqa_attention"],
    x: 2000,
    y: 1100,
  },
  {
    id: "ml_continuous_batching_orca",
    topicId: "ml_continuous_batching_orca",
    title: "Continuous Batching & Orca Schedulers",
    description:
      "Iteration-level scheduling, early request retirement, and throughput optimization.",
    family: "inference-serving",
    difficulty: "Hard",
    prerequisites: ["ml_flashattention_sram_tiling"],
    x: 1800,
    y: 1400,
  },
  {
    id: "ml_pagedattention_cow_vllm",
    topicId: "ml_pagedattention_cow_vllm",
    title: "PagedAttention & Copy-on-Write (vLLM)",
    description:
      "KV-cache memory fragmentation, logical-to-physical block translation, and sharing.",
    family: "inference-serving",
    difficulty: "Hard",
    prerequisites: ["ml_continuous_batching_orca"],
    x: 2200,
    y: 1400,
  },
  {
    id: "ml_speculative_decoding",
    topicId: "ml_speculative_decoding",
    title: "Speculative Decoding & Prefix Caching",
    description: "Draft model verification, tree attention, and exact-match prefix reuse.",
    family: "inference-serving",
    difficulty: "Hard",
    prerequisites: ["ml_pagedattention_cow_vllm"],
    x: 2600,
    y: 1400,
  },
  {
    id: "ml_floating_point_kahan",
    topicId: "ml_floating_point_kahan",
    title: "Floating-Point Formats & Kahan Summation",
    description:
      "FP32/FP16/BF16/FP8 representation, mantissa precision, and rounding error compensation.",
    family: "precision-kernels",
    difficulty: "Medium",
    prerequisites: ["ml_flashattention_sram_tiling"],
    x: 600,
    y: 1400,
  },
  {
    id: "ml_affine_quantization_int8",
    topicId: "ml_affine_quantization_int8",
    title: "Affine Quantization: INT8 & FP8",
    description: "Scale and zero-point calibration, weight-only vs activation quantization.",
    family: "precision-kernels",
    difficulty: "Hard",
    prerequisites: ["ml_floating_point_kahan"],
    x: 1000,
    y: 1400,
  },
  {
    id: "ml_dense_gemm_tiling",
    topicId: "ml_dense_gemm_tiling",
    title: "Dense GEMM & SRAM L1 Tiling",
    description:
      "Matrix multiplication kernels, arithmetic intensity, and hierarchical memory access.",
    family: "precision-kernels",
    difficulty: "Hard",
    prerequisites: ["ml_affine_quantization_int8"],
    x: 1400,
    y: 1400,
  },
  {
    id: "ml_interconnect_alpha_beta",
    topicId: "ml_interconnect_alpha_beta",
    title: "Interconnect Topologies & Alpha-Beta Cost Models",
    description: "Network latency, bandwidth constraints, and modeling communication overhead.",
    family: "distributed-compilers",
    difficulty: "Hard",
    prerequisites: ["ml_speculative_decoding", "ml_dense_gemm_tiling"],
    x: 1000,
    y: 1700,
  },
  {
    id: "ml_ring_allreduce_collective",
    topicId: "ml_ring_allreduce_collective",
    title: "Collective Communication & Ring-AllReduce",
    description: "Broadcast, scatter, gather, and bandwidth-optimal gradient reduction.",
    family: "distributed-compilers",
    difficulty: "Hard",
    prerequisites: ["ml_interconnect_alpha_beta"],
    x: 1300,
    y: 1700,
  },
  {
    id: "ml_zero3_parameter_sharding",
    topicId: "ml_zero3_parameter_sharding",
    title: "Distributed Sharding: ZeRO-1/2/3 & FSDP",
    description:
      "Partitioning optimizer states, gradients, and parameters across data-parallel ranks.",
    family: "distributed-compilers",
    difficulty: "Hard",
    prerequisites: ["ml_ring_allreduce_collective"],
    x: 1600,
    y: 1700,
  },
  {
    id: "ml_compiler_fusion_liveness",
    topicId: "ml_compiler_fusion_liveness",
    title: "Kernel Fusion & Buffer Liveness Memory Arenas",
    description: "Operator fusion, intermediate tensor elimination, and memory arena allocation.",
    family: "distributed-compilers",
    difficulty: "Hard",
    prerequisites: ["ml_zero3_parameter_sharding"],
    x: 1900,
    y: 1700,
  },
  {
    id: "ml_parallelism_3d_moe_1f1b",
    topicId: "ml_parallelism_3d_moe_1f1b",
    title: "3D Parallelism, 1F1B Scheduling & MoE Routing",
    description:
      "Tensor, pipeline, and data parallelism, bubble mitigation, and sparse expert routing.",
    family: "distributed-compilers",
    difficulty: "Hard",
    prerequisites: ["ml_compiler_fusion_liveness"],
    x: 2200,
    y: 1700,
  },
];

export const ML_INFRA_TREE_PLACEMENT_MAP = indexPlacements(ML_INFRA_TREE_PLACEMENTS);
