export { ArrayVisualizer } from "./ArrayVisualizer";
export type { ArrayVisualizerProps } from "./array/arrayTypes";

export { CanvasAuxiliaryOverlay } from "./CanvasAuxiliaryOverlay";
export type { CanvasAuxiliaryOverlayProps } from "./CanvasAuxiliaryOverlay";

export { GraphVisualizer } from "./GraphVisualizer";
export type { GraphVisualizerProps } from "./graph/graphTypes";

export { GridVisualizer } from "./GridVisualizer";
export type { GridVisualizerProps } from "./grid/gridTypes";

export { LineExplainPopover } from "./LineExplainPopover";
export type { LineExplainPopoverProps } from "./LineExplainPopover";

export { MatrixVisualizer } from "./MatrixVisualizer";
export type { MatrixVisualizerProps } from "./MatrixVisualizer";

export { ProblemHeader } from "./ProblemHeader";
export type { ProblemHeaderProps } from "./ProblemHeader";

export { QuantizationVisualizer } from "./QuantizationVisualizer";
export type { QuantizationVisualizerProps } from "./QuantizationVisualizer";

export { TreeVisualizer } from "./TreeVisualizer";
export type { TreeVisualizerProps } from "./tree/treeTypes";

export { VectorVisualizer } from "./VectorVisualizer";
export type { VectorVisualizerProps } from "./VectorVisualizer";

// New Reusable Primitives
export { IntervalVisualizer } from "./IntervalVisualizer";
export type { IntervalVisualizerProps } from "./IntervalVisualizer";

export { HeapVisualizer } from "./HeapVisualizer";
export type { HeapVisualizerProps } from "./HeapVisualizer";

export { DsuVisualizer } from "./DsuVisualizer";
export type { DsuVisualizerProps } from "./DsuVisualizer";

export { HashTableVisualizer } from "./HashTableVisualizer";
export type { HashTableVisualizerProps } from "./HashTableVisualizer";

export { StateSpaceVisualizer } from "./StateSpaceVisualizer";
export type { StateSpaceVisualizerProps } from "./StateSpaceVisualizer";

export { CallStackVisualizer } from "./CallStackVisualizer";
export type { CallStackVisualizerProps } from "./CallStackVisualizer";

export { BitmaskVisualizer } from "./BitmaskVisualizer";
export type { BitmaskVisualizerProps } from "./BitmaskVisualizer";

export { AttentionMapVisualizer } from "./AttentionMapVisualizer";
export type { AttentionMapVisualizerProps } from "./AttentionMapVisualizer";

export { TrieVisualizer } from "./TrieVisualizer";
export type { TrieVisualizerProps } from "./TrieVisualizer";

export {
  CompositeVisualizer,
  RenderPrimitiveSnapshot,
  isRenderablePrimitiveSnapshot,
} from "./CompositeVisualizer";
export type { CompositeVisualizerProps, RenderPrimitiveSnapshotProps } from "./CompositeVisualizer";

// In-Canvas Visualizer Primitives
export { DinicFlowVisualizer } from "./DinicFlowVisualizer";
export { FenwickTreeVisualizer } from "./FenwickTreeVisualizer";
export { ConvexHullSweepVisualizer } from "./ConvexHullSweepVisualizer";
export { FlashAttentionTileVisualizer } from "./FlashAttentionTileVisualizer";
export { RingAllReduceVisualizer } from "./RingAllReduceVisualizer";
export { PagedAttentionBlockVisualizer } from "./PagedAttentionBlockVisualizer";
export { RMSNormVisualizer } from "./RMSNormVisualizer";
export { Im2ColGEMMVisualizer } from "./Im2ColGEMMVisualizer";
export { MLPBackpropVisualizer } from "./MLPBackpropVisualizer";
export {
  VectorCalculusAutodiffStudio,
  AUTODIFF_PRESETS,
  evaluateGraphForward,
  evaluateGraphReverse,
  computeExactHessian,
  computeHessianVectorProduct,
  computeFiniteDifferenceHVP,
  computeJacobianMatrix,
  computeVectorFieldCalculus,
} from "./VectorCalculusAutodiffStudio";
export type {
  VectorCalculusAutodiffStudioProps,
  AutodiffMode,
  AutodiffPresetId,
  OpType,
  GraphNode,
  ForwardNodeTrace,
  ForwardResult,
  ReverseStepTrace,
  ReverseResult,
  RNodeTrace,
  HessianVectorProductResult,
  VectorCalculusResult,
  AutodiffPreset,
} from "./VectorCalculusAutodiffStudio";

export {
  SpectralSVDGeometryStudio,
  SPECTRAL_STUDIO_PRESETS,
  computeSVD2x2,
  computeEigendecomposition2x2,
  computeGramSchmidt2x2,
  computeMahalanobis2x2,
  computeMatrixProperties2x2,
} from "./SpectralSVDGeometryStudio";
export type {
  SpectralSVDGeometryStudioProps,
  SpectralStudioMode,
  SpectralPresetId,
  Matrix2x2,
  Vector2,
  ComplexNumber,
  SVDResult2x2,
  EigenClassification,
  EigenResult2x2,
  GramSchmidtResult2x2,
  ConfidenceEllipseInfo,
  MahalanobisResult2x2,
  MatrixProperties2x2,
  SpectralPreset,
} from "./SpectralSVDGeometryStudio";

export {
  VectorDBRetrievalWorkbench,
  VECTOR_DB_PRESETS,
  euclideanDistance,
  cosineDistance,
  dotProductSimilarity,
  manhattanDistance,
  computeDistance,
  generateVectorDataset,
  flatScanSearch,
  buildKDTree,
  kdTreeSearch,
  buildIVFIndex,
  ivfSearch,
  buildPQIndex,
  computeADCTable,
  pqSearch,
  buildHNSWIndex,
  hnswSearch,
  calculateRecallAtK,
  generateRecallVsLatencyCurve,
} from "./VectorDBRetrievalWorkbench";
export type {
  VectorDBRetrievalWorkbenchProps,
  DistanceMetric,
  RetrievalAlgorithm,
  DatasetDistribution,
  VectorPoint,
  DatasetConfig,
  SearchTraceAction,
  SearchTraceStep,
  NeighborCandidate,
  SearchResult,
  BoundingBox2D,
  KDNode,
  IVFClusterCentroid,
  IVFIndex,
  PQIndex,
  HNSWNode,
  HNSWIndex,
  BenchmarkPoint,
  PresetId,
  VectorDBPreset,
} from "./VectorDBRetrievalWorkbench";

export {
  GraphNetworkFlowStudio,
  NETWORK_FLOW_PRESETS,
  FLOW_ALGORITHMS,
  edgeKey,
  computeResidualCapacityMap,
  computeResidualGraph,
  computeLevelGraphBFS,
  computeMinCutPartition,
  computeFlowTelemetry,
  verifyFlowConservation,
  verifyCapacityConstraints,
  solveEdmondsKarp,
  solveDinic,
  solvePushRelabel,
  solveMinCostMaxFlow,
  executeFlowAlgorithm,
  formatFlow,
  formatCost,
  runDinicAlgorithm,
  runEdmondsKarpAlgorithm,
  runPushRelabelAlgorithm,
  runBellmanFordDijkstra,
} from "./GraphNetworkFlowStudio";

export type {
  GraphNetworkFlowStudioProps,
  FlowAlgorithmMode,
  FlowAlgorithmId,
  NetworkFlowPresetId,
  FlowPresetId,
  EdgeLabelDisplayMode,
  FlowStudioViewMode,
  NetworkFlowNode,
  FlowNode,
  NetworkFlowEdge,
  FlowEdge,
  FlowGraph,
  ResidualEdge,
  AugmentingStep,
  MinCutPartition,
  MinCutPartitionResult,
  PushRelabelNodeState,
  FlowTelemetry,
  FlowStepTrace,
  NetworkFlowPreset,
  FlowPresetConfig,
  FlowConservationStatus,
  FlowComputationResult,
  AlgorithmSimulationResult,
  ShortestPathSimulationResult,
  FlowAlgorithmSpec,
} from "./GraphNetworkFlowStudio";

export {
  OptimizationLandscapeStudio,
  OPTIMIZATION_LANDSCAPES,
  OPTIMIZER_CONFIGS,
  computeNumericalGradient,
  computeNumericalHessian,
  compute2x2SymmetricEigen,
  simulateOptimizerStep,
  simulateFullTrajectory,
  simulateAllOptimizers,
} from "./OptimizationLandscapeStudio";
export type {
  OptimizationLandscapeStudioProps,
  LandscapeId,
  OptimizerId,
  StudioViewMode,
  Vector2D,
  CurvatureType,
  EigenResult,
  Domain2D,
  LandscapeDefinition,
  OptimizerHyperparameters,
  OptimizerConfig,
  TrajectoryPoint,
  TrajectoryResult,
  OptimizerStepState,
} from "./OptimizationLandscapeStudio";

export {
  TokenizerAutomataStudio,
  TOKENIZER_PRESETS,
  TIKTOKEN_PATTERNS,
  buildInitialVocab,
  countPairFrequencies,
  trainBPE,
  tokenizeBPE,
  getBPEMergeTrace,
  classifyPreTokenChunk,
  splitTiktokenRegex,
  encodeUTF8Bytes,
  decodeUTF8Bytes,
  bytesToHex,
  bytesToBinary,
  gpt2BytesToUnicodeMapping,
  getByteFallbackTokens,
  buildAhoCorasickTrie,
  buildAhoCorasickAutomata,
  searchAhoCorasick,
  layoutAhoCorasickGraph,
} from "./TokenizerAutomataStudio";
export type {
  TokenizerAutomataStudioProps,
  TokenizerStudioMode,
  TokenizerPresetId,
  BPEMergeRule,
  BPEVocabItem,
  BPEMergeTraceStep,
  PreTokenCategory,
  PreTokenChunk,
  ByteTokenInfo,
  AhoCorasickNode,
  AhoCorasickAutomata,
  AhoCorasickMatch,
  AhoCorasickStepTrace,
  LayoutGraphNode,
  LayoutGraphEdge,
  TokenizerPreset,
} from "./TokenizerAutomataStudio";

export {
  ContinuousSpeculativeServingStudio,
  CONTINUOUS_SERVING_PRESETS,
  computeRejectionSamplingAcceptance,
  computeResidualDistribution,
  sampleResidualToken,
  computeExpectedAcceptedTokens,
  computeSpeculativeSpeedup,
  generateSpeculativeDraftTree,
  createTreeAttentionMask,
  splitPrefillIntoChunks,
  calculateContinuousBatchingEfficiency,
  scheduleOrcaIterationStep,
} from "./ContinuousSpeculativeServingStudio";
export type {
  ContinuousServingStudioProps,
  ServingPresetId,
  ServingPreset,
  RequestStatus,
  SpeculativeMode,
  TokenProbability,
  SpeculativeDraftNode,
  SpeculativeStepResult,
  InferenceRequest,
  BatchSchedulerState,
  SchedulerConfig,
} from "./ContinuousSpeculativeServingStudio";

export {
  MoEExpertParallelStudio,
  MOE_PRESETS,
  PIPELINE_STEPS,
  softmax,
  computeTopKRouting,
  computeDeepSeekBiasRouting,
  updateDeepSeekBiases,
  simulateDeepSeekBiasConvergence,
  computeAuxiliaryLoss,
  calculateExpertCapacity,
  generateDeterministicLogits,
  simulateAllToAllDispatchCombine,
  calculateMoeCommunicationVolume,
  calculateExpertLoadImbalance,
  formatBytes,
  getGpuColor,
} from "./MoEExpertParallelStudio";
export type {
  MoEExpertParallelStudioProps,
  MoEPresetId,
  PipelineStepId,
  RoutingBiasType,
  RoutingStrategy,
  MoEConfig,
  TokenAssignment,
  TokenData,
  AllToAllResult,
  DeepSeekBiasRoutingResult,
  BiasConvergenceIteration,
  MoEPreset,
  PipelineStepMeta,
} from "./MoEExpertParallelStudio";

export {
  ProbabilisticSamplingStudio,
  DEFAULT_GMM_CONFIG,
  DEFAULT_ROSENBROCK_CONFIG,
  DEFAULT_DOUGHNUT_CONFIG,
  DEFAULT_BIVARIATE_GAUSSIAN_CONFIG,
  DEFAULT_DISCRETE_TOKENS,
  SAMPLING_PRESETS,
  invertMatrix2x2,
  mahalanobisQuad2D,
  sampleStandardNormal,
  sampleNormal2D,
  computeEnergyGMM,
  computeGradientGMM,
  computeEnergyRosenbrock,
  computeGradientRosenbrock,
  computeEnergyDoughnut,
  computeGradientDoughnut,
  computeEnergyBivariateGaussian,
  computeGradientBivariateGaussian,
  stepMetropolisHastings,
  stepGibbsGaussian,
  stepGibbsGMM,
  runLeapfrogIntegrator,
  stepHamiltonianMonteCarlo,
  computeSoftmaxWithTemperature,
  filterTopK,
  filterTopP,
  filterTopKTopP,
  sampleCategorical,
  stepDiscreteSampling,
  computeAutocorrelation,
  computeEffectiveSampleSize,
  computeSampleMeanAndCovariance,
  compute1DMarginalHistogram,
} from "./ProbabilisticSamplingStudio";
export type {
  TargetDistributionId,
  SamplingAlgorithmId,
  SamplingPresetId,
  GMMComponent,
  GMMConfig,
  RosenbrockConfig,
  DoughnutConfig,
  BivariateGaussianConfig,
  DiscreteTokenItem,
  MHStepResult,
  GibbsStepResult,
  HMCStepResult,
  DiscreteStepResult,
  SampleHistoryItem,
  ChainDiagnostics,
  SamplingPreset,
  ProbabilisticSamplingStudioProps,
} from "./ProbabilisticSamplingStudio";

export {
  DPTreeDecompositionStudio,
  DP_TREE_MODALITIES,
  DP_TREE_PRESETS,
  TREE_DIAMETER_PRESETS,
  HLD_PRESETS,
  LCA_PRESETS,
  CHT_PRESETS,
  buildTreeFromEdges,
  computeTwoDFS,
  computeTreeDiameterDP,
  computeHLD,
  queryHLDPath,
  buildBinaryLiftingTable,
  queryLCA,
  computeLineIntersection,
  buildConvexHullTrick,
  queryCHT,
  computeTreeLayout,
} from "./DPTreeDecompositionStudio";
export type {
  DPTreeStudioModality,
  TreeNode,
  TreeEdge,
  TreeGraph,
  TreeDiameterDPResult,
  TwoDFSResult,
  HLDResult,
  HLDPathInterval,
  HLDPathQueryResult,
  BinaryLiftingTable,
  LCAJumpStep,
  LCASimultaneousJumpStep,
  LCAQueryResult,
  CHTLine,
  CHTIntersection,
  CHTPoppedLine,
  CHTHistoryStep,
  CHTEnvelopeResult,
  CHTLineEvaluation,
  CHTQueryResult,
  DPTreeDecompositionStudioProps,
  DPTreePresetConfig,
} from "./DPTreeDecompositionStudio";

export {
  LoRAGradientCheckpointingStudio,
  NF4_QUANTILES,
  GPU_HARDWARE_SPECS,
  ALL_TARGET_MODULES,
  LORA_STUDIO_PRESETS,
  quantizeNF4,
  dequantizeNF4,
  computeDoubleQuantizationSavings,
  computeQuantizationMetrics,
  computeLoRAParameters,
  generateLoRAMatrices,
  computeSVDSpectrum,
  computeFullVsLoRAMemoryBreakdown,
  computeCheckpointingTradeoffs,
  evaluateGpuHardwareFit,
  simulateLoRAForwardBackwardStep,
  generateTrainingPipelineSteps,
} from "./LoRAGradientCheckpointingStudio";
export type {
  LoRAStudioTabId,
  LoRAPresetId,
  BasePrecision,
  CheckpointingMode,
  OptimizerType,
  TargetModule,
  LoRAStudioConfig,
  LoRAPreset,
  GpuHardwareSpec,
  HardwareStatus,
  HardwareFitEvaluation,
  MemoryBreakdownItem,
  MemoryBreakdown,
  CheckpointingTradeoff,
  TrainingPipelineStep,
  SVDSpectrumResult,
  LoRAStudioProps,
} from "./LoRAGradientCheckpointingStudio";

export {
  GaussianProcessesKernelStudio,
  evaluateKernel,
  evaluateKernelComposed,
  computeGramMatrix,
  choleskyDecomposition,
  forwardSubstitution,
  backwardSubstitution,
  choleskySolve,
  createDeterministicRng,
  sampleStandardNormal as sampleStandardNormalGP,
  sampleMultivariateNormal,
  computeMarginalLogLikelihood,
  computeRKHSNorm,
  computeGramEigenvalues,
  fitGPRegression,
  GP_PRESETS,
  DEFAULT_GP_HYPERPARAMS,
  KERNEL_DEFINITIONS,
} from "./GaussianProcessesKernelStudio";
export type {
  KernelType,
  KernelCompositionMode,
  KernelHyperparameters,
  ComposedKernelConfig,
  GPObservationPoint,
  MarginalLogLikelihoodResult,
  EigenSpectrumResult,
  GPRegressionResult,
  GPPresetId,
  GPPreset,
  StudioTab,
  KernelMetaInfo,
  GaussianProcessesKernelStudioProps,
} from "./GaussianProcessesKernelStudio";

export {
  ComputationalGeometrySweepStudio,
  crossProduct2D,
  turnOrientation,
  euclideanDistance as euclideanDistance2D,
  euclideanDistanceSquared,
  shoelacePolygonArea,
  polygonPerimeter,
  computeMonotoneChain,
  computeGrahamScan,
  computeQuickHull,
  lineSegmentIntersection,
  computeBentleyOttmann,
  computeClosestPairBruteForce,
  computeClosestPairDC,
  isPointOnSegment,
  computeRayCastingPIP,
  computeWindingNumberPIP,
  GEOMETRY_MODALITIES,
  CONVEX_HULL_PRESETS,
  BENTLEY_OTTMANN_PRESETS,
  CLOSEST_PAIR_PRESETS,
  POINT_IN_POLYGON_PRESETS,
  GEOMETRY_STUDIO_PRESETS,
} from "./ComputationalGeometrySweepStudio";
export type {
  GeometryStudioModality,
  ConvexHullAlgorithmId,
  Point2D,
  LineSegment,
  TurnOrientation,
  ConvexHullStep,
  ConvexHullAlgorithmResult,
  BentleyOttmannEventType,
  SweepEvent,
  IntersectionPoint,
  BentleyOttmannStep,
  BentleyOttmannResult,
  ClosestPairCandidate,
  ClosestPairStep,
  ClosestPairDCResult,
  ClosestPairResult,
  RayCastingEdgeTrace,
  PIPStepTrace,
  RayCastingPIPResult,
  WindingNumberEdgeTrace,
  WindingNumberPIPResult,
  GeometryStudioPreset,
  ComputationalGeometrySweepStudioProps,
} from "./ComputationalGeometrySweepStudio";

export {
  SuffixAutomataStudio,
  buildSuffixAutomaton,
  buildSuffixAutomatonStepByStep,
  buildSuffixArray,
  computeKasaiLCP,
  queryLCPInterval,
  countDistinctSubstringsSAM,
  computeDAGSubstringsDP,
  findKthSubstring,
  searchPatternSAM,
  computeEndposOccurrences,
  layoutSAMGraph,
  SAM_STUDIO_PRESETS,
} from "./SuffixAutomataStudio";
export type {
  SAMStudioModality,
  SAMPresetId,
  SAMState,
  SuffixAutomaton,
  SAMConstructionPhase,
  SAMStepTrace,
  SuffixArrayResult,
  KasaiStepTrace,
  KasaiLCPResult,
  LCPQueryResult,
  DAGSubstringsDPResult,
  KthSubstringResult,
  SAMPatternSearchResult,
  EndposPropagationResult,
  SAMGraphNode,
  SAMGraphEdge,
  SAMGraphLayout,
  SAMPreset,
  SuffixAutomataStudioProps,
} from "./SuffixAutomataStudio";

export {
  TritonKernelTilingStudio,
  computeTilingGrid,
  computeProgramIdRemapping,
  calculateL2CacheHitRate,
  calculateBankAddresses,
  detectBankConflicts,
  applyXORSwizzle,
  applyXorSwizzleAddress,
  simulateAsyncPipeline,
  computeRooflineMetrics,
  generateTritonKernelCode,
  GPU_ARCH_PROFILES,
  DATA_TYPE_SPECS,
  TRITON_TILING_PRESETS,
} from "./TritonKernelTilingStudio";
export type {
  GPUArchId,
  GPUArchSpec,
  DataTypeId,
  DataTypeSpec,
  TilingConfig,
  TritonPresetId,
  TritonPreset,
  BankAccess,
  BankConflictReport,
  PipelineStepStageState,
  PipelineStepState,
  PipelineSimulationResult,
  RooflineMetrics,
  TritonKernelTilingStudioProps,
} from "./TritonKernelTilingStudio";

export {
  ManifoldLearningStudio,
  createDeterministicRng as createDeterministicRngManifold,
  sampleNormal as sampleNormalManifold,
  computePairwiseDistances as computePairwiseDistancesManifold,
  computePairwiseSquaredDistances as computePairwiseSquaredDistancesManifold,
  computeSymmetricEigenvaluesAndVectors,
  getManifoldColor,
  generateSwissRoll,
  generateConcentricSpheres,
  generateSeveredSphere,
  generateTwinPeaks,
  generateTrefoilKnot,
  generateInterlockingRings,
  generateManifoldDataset,
  computePCA,
  computeTSNEPerplexitySigma,
  computeTSNESymmetrizedP,
  computeTSNEStudentTDist,
  computeTSNEGradient,
  computeTSNEKLLoss,
  stepTSNE,
  computeUMAPLocalMetrics,
  computeUMAPFuzzyUnion,
  findUMAPABParams,
  computeUMAPGradient,
  stepUMAP,
  buildKNNGraph,
  computeAllPairsShortestPathsDijkstra,
  classicalMDS,
  computeIsomap,
  computeTrustworthiness,
  computeContinuity,
  computeNeighborhoodPreservationRatio,
  computeManifoldDiagnostics,
  project3DTo2D,
  MANIFOLD_DATASETS,
  DEFAULT_HYPERPARAMS as DEFAULT_MANIFOLD_HYPERPARAMS,
  MANIFOLD_PRESETS,
  ALGORITHM_META as MANIFOLD_ALGORITHM_META,
} from "./ManifoldLearningStudio";
export type {
  Point3D,
  Point2D as ManifoldPoint2D,
  ManifoldDatasetId,
  ManifoldAlgorithmId,
  ManifoldPresetId,
  ManifoldDatasetMeta,
  GeneratedDataset as GeneratedManifoldDataset,
  AlgorithmHyperparameters as ManifoldAlgorithmHyperparameters,
  ManifoldPreset,
  ManifoldDiagnostics,
  AlgorithmState as ManifoldAlgorithmState,
  PCAResult,
  MDSResult,
  IsomapResult,
  UMAPParams,
  TSNEParams,
  Camera3D,
  ManifoldLearningStudioProps,
} from "./ManifoldLearningStudio";

export {
  QuantizationAWQStudio,
  floatToFP8E4M3,
  fp8E4M3ToFloat,
  floatToFP8E5M2,
  fp8E5M2ToFloat,
  decomposeFP8,
  quantizeINT4Groupwise,
  computeActivationSalience,
  gemmMatrixMultiply,
  searchOptimalAWQAlpha,
  applySmoothQuantTransform,
  computeFrobeniusError,
  computeSQNR,
  computeCosineSimilarity,
  computeMAE,
  computeMaxError,
  estimatePerplexityDelta,
  calculateMemorySavings,
  computeErrorHistogramBins,
  generatePresetMatrices,
  QUANTIZATION_AWQ_PRESETS,
} from "./QuantizationAWQStudio";
export type {
  FP8FormatType,
  INT4Scheme,
  INT4GroupSizeOption,
  QuantStudioTabId,
  QuantizationPresetId,
  FP8BitDecomposition,
  INT4QuantOptions,
  INT4GroupData,
  INT4QuantResult,
  AWQSearchOptions,
  AWQSweepPoint,
  AWQSearchResult,
  SmoothQuantChannelData,
  SmoothQuantResult,
  FrobeniusResult,
  PerplexityDeltaResult,
  MemorySavingsResult,
  HistogramBin,
  PresetData,
  QuantizationPreset,
  QuantizationAWQStudioProps,
} from "./QuantizationAWQStudio";

export {
  DiffusionScoreMatchingStudio,
  SeededRNG,
  norm2D,
  computeLinearSchedule,
  computeCosineSchedule,
  computeSigmoidSchedule,
  buildNoiseSchedule,
  generateDiffusionDataset,
  qSample,
  computeExactScore,
  scoreToEpsilon,
  epsilonToScore,
  predictX0FromEps,
  predictX0FromScore,
  computeCFGScore,
  ddpmReverseStep,
  ddimReverseStep,
  evaluateContinuousVPDriftAndDiffusion,
  evaluateContinuousVEDriftAndDiffusion,
  computeScoreVectorField,
  computeELBOBreakdown,
  DIFFUSION_STUDIO_PRESETS,
} from "./DiffusionScoreMatchingStudio";
export type {
  DiffusionDatasetId,
  DiffusionFrameworkId,
  NoiseScheduleType,
  DiffusionStudioTabId,
  DiffusionPresetId,
  DiffusionDatasetPoint,
  NoiseSchedule,
  ScoreEvaluation,
  ParticleState,
  VectorFieldCell,
  ELBOBreakdown,
  ContinuousSDEParams,
  SimulationHistoryStep,
  DiffusionPreset,
  DiffusionScoreMatchingStudioProps,
} from "./DiffusionScoreMatchingStudio";

export {
  SpatialIndexBVHStudio,
  EPSILON as SPATIAL_EPSILON,
  euclideanDistance2D as spatialEuclideanDistance2D,
  euclideanDistanceSquared2D,
  aabbUnion,
  aabbFromPoints,
  aabbArea,
  aabbHalfArea,
  aabbIntersection,
  aabbIntersectBox,
  pointToAABBDistanceMin,
  pointToAABBDistanceMax,
  rayAABBIntersect,
  rayCircleIntersect,
  raySegmentIntersect,
  rayPrimitiveIntersect,
  buildKDTree2D,
  collectKDTreeLines,
  generateKDSplitSteps,
  getTreeDepth as getKDTreeDepth,
  countTreeNodes as countKDTreeNodes,
  findKNearestNeighbors,
  generateKNNSteps,
  pickSeeds,
  pickNext,
  quadraticSplit,
  buildRTree2D,
  queryRTreeRange,
  generateRTreeRangeQuerySteps,
  computeSAHCost,
  buildBVHWithSAH,
  traverseBVHRay,
  generateBVHRaySteps,
  SPATIAL_INDEX_MODALITIES,
  KD_TREE_PRESETS,
  KNN_QUERY_PRESETS,
  RTREE_PRESETS,
  BVH_SAH_PRESETS,
  SPATIAL_INDEX_PRESETS,
} from "./SpatialIndexBVHStudio";
export type {
  SpatialModality,
  Point2D as SpatialPoint2D,
  AABB as SpatialAABB,
  Ray2D,
  KDTreeAxis,
  KDSplitLine,
  KDTreeNode,
  KDSplitStep,
  NeighborCandidate as SpatialNeighborCandidate,
  KNNStepTrace,
  KNNResult,
  RTreeEntry,
  RTreeNode,
  RTreeRangeStepTrace,
  RTreeRangeResult,
  BVHPrimitiveType,
  BVHPrimitive,
  BVHNode,
  BVHBuildOptions,
  RayHit,
  BVHRayStepTrace,
  BVHRayResult,
  SpatialStudioPreset,
  SpatialModalityInfo,
  SpatialIndexBVHStudioProps,
} from "./SpatialIndexBVHStudio";

export {
  FSDPZeROShardingStudio,
  getPrecisionBytes,
  getOptimizerBytesPerParam,
  calculateModelParamCount,
  calculateActivationMemory,
  calculateWorkingTransientBuffer,
  calculateMemoryBreakdown,
  calculateCollectiveCommunication,
  calculateOffloadingTimeline,
  generateTrainingStepperSteps,
  calculateMaxBatchSize,
  calculateClusterScalingSweep,
  formatBytes as formatFSDPBytes,
  formatFlops,
  formatBandwidth,
  generatePyTorchFSDPCode,
  generateDeepSpeedConfig,
  getInterconnectBandwidthGbs,
  getGpuSpec as getFSDPGpuSpec,
  GPU_HARDWARE_SPECS as FSDP_GPU_HARDWARE_SPECS,
  INTERCONNECT_SPECS,
  FSDP_PRESETS,
} from "./FSDPZeROShardingStudio";
export type {
  ShardingStrategy,
  PrecisionFormat,
  OptimizerType as FSDPOptimizerType,
  OffloadTarget,
  InterconnectType,
  ActivationCheckpointingMode,
  FSDPPresetId,
  FSDPStudioTabId,
  GpuHardwareSpec as FSDPGpuHardwareSpec,
  InterconnectSpec,
  ModelArchitectureConfig,
  ClusterConfig,
  TrainingConfig,
  MemoryItem,
  MemoryBreakdownResult,
  CommunicationAnalysisResult,
  StepSimulationState,
  OffloadingAnalysisResult,
  FSDPPreset,
  FSDPZeROShardingStudioProps,
} from "./FSDPZeROShardingStudio";

export {
  ReinforcementLearningStudio,
  ACTION_NAMES,
  ACTION_ARROWS,
  ACTION_DELTAS,
  DEFAULT_CARTPOLE_CONFIG,
  GRID_CONFIG_4X4_CLASSIC,
  GRID_CONFIG_CLIFF_WALKING,
  GRID_CONFIG_OBSTACLE_MAZE,
  GRID_CONFIG_SLIPPERY_FROZEN,
  GRIDWORLD_CONFIGS,
  RL_PRESETS,
  coordToStateIndex,
  stateIndexToCoord,
  getGridNextCoord,
  createGridworldMDP,
  stepGridworld,
  computeBellmanOptimalUpdate,
  stepValueIteration,
  solveValueIteration,
  evaluatePolicyIterative,
  evaluatePolicyExact,
  solveLinearSystem,
  improvePolicy,
  solvePolicyIteration,
  qLearningStep,
  selectEpsilonGreedyAction,
  computeEpsilonDecay,
  runQLearningEpisode,
  computeGAE,
  computePPOClippedObjective,
  generatePPOClippingCurve,
  computeSoftmaxLogits,
  computeCartPoleDerivatives,
  stepCartPolePhysics,
  resetCartPole,
  getValueColor,
} from "./ReinforcementLearningStudio";
export type {
  RLAlgorithmId,
  RLEnvironmentId,
  RLPresetId,
  GridAction,
  CartPoleAction,
  GridCoord,
  GridGoalConfig,
  GridCliffConfig,
  GridworldConfig,
  TransitionOutcome,
  GridworldMDP,
  BellmanStepResult,
  ValueIterationIterationResult,
  ValueIterationSolveResult,
  PolicyIterationResult,
  QLearningStepResult,
  QLearningEpisodeResult,
  GAEResult,
  PPOClippedObjectiveResult,
  PPOClippingPoint,
  CartPoleState,
  CartPoleConfig,
  CartPoleStepResult,
  RLPreset,
  ReinforcementLearningStudioProps,
} from "./ReinforcementLearningStudio";

export {
  AhoCorasickAutomataStudio,
  GraphCanvasView,
  AHO_CORASICK_PRESETS,
  MODALITY_CONFIGS as AHO_CORASICK_MODALITY_CONFIGS,
  cloneACTrie,
  createEmptyACTrie,
  validatePatterns as validateACPatterns,
  getNodePrefixPath,
  buildACTrie,
  generateTrieBuildTrace,
  computeFailureLinks,
  generateFailureLinksTrace,
  computeDictSuffixLinks,
  collectChainOutputs,
  generateDictSuffixLinksTrace,
  buildFullAhoCorasick,
  computeDFATransitionMatrix,
  searchAhoCorasick as searchAhoCorasickStudio,
  searchAhoCorasick as searchACTrie,
  searchAhoCorasick as searchAhoCorasickACTrie,
  naiveMultiPatternSearch,
  generateStreamingSearchTrace,
  layoutACTrie,
} from "./AhoCorasickAutomataStudio";
export type {
  AhoCorasickModality,
  ACPresetId,
  ACTrieNode,
  ACTrie,
  ACMatchOccurrence,
  ACTransitionMatrix,
  ACTrieBuildAction,
  ACTrieBuildStep,
  ACFailLinkPhase,
  ACFailLinkBuildStep,
  ACDictLinkPhase,
  ACDictLinkBuildStep,
  ACSearchTransitionType,
  ACSearchStep,
  ACLayoutNode,
  ACLayoutEdge,
  ACLayoutResult,
  ACPreset,
  AhoCorasickAutomataStudioProps,
} from "./AhoCorasickAutomataStudio";

export {
  InterconnectTopologyStudio,
  LINK_TECHNOLOGIES,
  COLLECTIVE_ALGORITHMS,
  TOPOLOGY_PRESETS,
  computeBisectionBandwidth,
  computeTopologyHopCount,
  computeHockneyLatency,
  calculateAlgorithmComparison,
  generateCollectiveSteps,
  formatBytes as formatTopologyBytes,
  formatTime as formatTopologyTime,
  formatBandwidth as formatTopologyBandwidth,
} from "./InterconnectTopologyStudio";
export type {
  TopologyType,
  LinkTechId,
  CollectiveAlgorithmId,
  ChunkStatus,
  LinkTechnology,
  TopologyConfig,
  CollectiveAlgorithmConfig,
  HockneyLatencyBreakdown,
  CollectivePacketTransfer,
  RankChunkState,
  RankState,
  CollectiveStep,
  PresetConfig as TopologyPresetConfig,
  InterconnectTopologyStudioProps,
} from "./InterconnectTopologyStudio";

export {
  TarjanSCC2SATStudio,
  SCC_PALETTE,
  MODALITY_CONFIGS as TARJAN_MODALITY_CONFIGS,
  TARJAN_2SAT_PRESETS,
  runTarjanSCC,
  findBridgesAndArticulationPoints,
  buildCondensationGraph,
  parse2SATFormula,
  build2SATImplicationGraph,
  solve2SAT,
  evaluate2SATFormula,
  generateTarjanSteps,
  negateLiteral as negate2SATLiteral,
  format2SATLiteral,
  format2SATClause,
  format2SATFormula,
} from "./TarjanSCC2SATStudio";
export type {
  TarjanStudioModality,
  TarjanPresetId,
  TarjanGraphNode,
  TarjanGraphEdge,
  TarjanGraph,
  TarjanSCCResult,
  BridgeEdgeInfo,
  BridgesArticulationResult,
  CondensationNode,
  CondensationEdge,
  CondensationGraphResult,
  TwoSATLiteral,
  TwoSATClause,
  TwoSATFormula,
  TwoSATImplicationEdge,
  TwoSATImplicationGraph,
  TwoSATContradiction,
  TwoSATClauseEvaluation,
  TwoSATSolverResult,
  TarjanStepAction,
  TarjanTelemetry,
  TarjanAnimationStep,
  TarjanPreset,
  ModalityConfig as TarjanModalityConfig,
  TarjanSCC2SATStudioProps,
} from "./TarjanSCC2SATStudio";

export {
  PipelineTensorParallelStudio,
  GPU_HARDWARE_SPECS as PIPELINE_GPU_HARDWARE_SPECS,
  GPU_HARDWARE_SPECS as PARALLEL_3D_GPU_HARDWARE_SPECS,
  PARALLEL_PRESETS,
  getBytesPerElement,
  getOptimizerBytesPerParam as getPipelineOptimizerBytesPerParam,
  calculate3DMemoryBreakdown,
  computeBubbleFraction,
  generatePipelineSchedule,
  computeCommunicationVolume,
  computeMFUAndThroughput,
  computeTensorParallelGEMMTrace,
  computeSequenceParallelSavings,
  generateDeviceMeshMapping,
  generateMegatronLaunchCommand,
  generatePyTorchDeviceMeshCode,
  generateDeepSpeed3DConfig,
  formatBytes as format3DParallelBytes,
  formatFLOPs,
  formatTokensPerSec,
  formatLatencyMs,
} from "./PipelineTensorParallelStudio";
export type {
  ParallelPresetId,
  StudioTabId,
  PipelineType,
  PrecisionFormat as PipelinePrecisionFormat,
  OptimizerType as PipelineOptimizerType,
  ActivationCheckpointMode,
  ZeROStage,
  SequenceParallelType,
  GpuHardwareSpec as PipelineGpuHardwareSpec,
  ModelArchitectureConfig as PipelineModelArchitectureConfig,
  ParallelismConfig,
  MemoryBreakdownResult as PipelineMemoryBreakdownResult,
  CommunicationVolumeResult,
  MFUThroughputResult,
  PipelineScheduleEvent,
  PipelineScheduleResult,
  TensorParallelGEMMStep,
  TensorParallelTraceResult,
  SequenceParallelSavingsResult,
  DeviceMeshCoordinate,
  DeviceMeshMappingResult,
  ParallelPreset,
  PipelineTensorParallelStudioProps,
} from "./PipelineTensorParallelStudio";

export {
  GraphNeuralNetworkStudio,
  GNN_PRESETS,
  zerosMatrix,
  identityMatrix,
  cloneMatrix,
  matrixAdd,
  matrixSubtract,
  matrixMultiply,
  matrixVectorMultiply,
  matrixTranspose,
  dotProduct,
  vectorNorm,
  vectorNormalize,
  vectorCosineSimilarity,
  applyActivation,
  applyActivationMatrix,
  computeAdjacencyMatrix,
  computeDegreeVector,
  computeDegreeMatrix,
  computeNormalizedAdjacency,
  computeLaplacian,
  computeNormalizedLaplacian,
  computeRandomWalkLaplacian,
  computeEigenvaluesAndVectors,
  computeGraphFourierTransform,
  computeInverseGraphFourierTransform,
  computeChebyshevFilter,
  computeGCNLayer,
  computeGraphSAGELayer,
  computeGATLayer,
  computeGINLayer,
  computeDirichletEnergy,
  computeUnnormalizedDirichletEnergy,
  computeCosineSimilarityMatrix,
  computeAveragePairwiseCosineDistance,
  simulateLayerTrajectories,
  run1WLColorRefinement,
  compare1WLGraphPair,
  getWLColorHex,
  getHarmonicColor,
} from "./GraphNeuralNetworkStudio";
export type {
  GNNStudioTab,
  MessagePassingArchitecture,
  GraphSageAggregator,
  ActivationFunction as GNNActivationFunction,
  GNNPresetId,
  GNNNode,
  GNNEdge,
  GNNGraphPreset,
  SpectralDecompositionResult,
  WLRefinementStep,
  WLRefinementResult,
  WLComparisonResult,
  TrajectoryPoint as GNNTrajectoryPoint,
  GraphNeuralNetworkStudioProps,
} from "./GraphNeuralNetworkStudio";

export {
  TreapSplayTreeStudio,
  TREAP_SPLAY_PRESETS,
  generateUniqueNodeId,
  getCartesianSize,
  createCartesianNode,
  updateCartesianSize,
  cloneCartesianTree,
  splitCartesian,
  mergeCartesian,
  insertCartesian,
  deleteCartesian,
  findCartesian,
  kthCartesian,
  collectCartesianInOrder,
  computeCartesianHeight,
  validateCartesianTreap,
  getImplicitSize,
  createImplicitNode,
  pushDownImplicit,
  updateImplicitSize,
  splitImplicit,
  mergeImplicit,
  reverseRangeImplicit,
  cyclicShiftImplicit,
  insertAtImplicit,
  deleteAtImplicit,
  extractImplicitArray,
  computeImplicitHeight,
  validateImplicitTreap,
  getSplaySize,
  createSplayNode,
  updateSplaySize,
  rotateRightSplay,
  rotateLeftSplay,
  calculateSplayPotentialPhi,
  computeSplayHeight,
  splayTree,
  insertSplay,
  deleteSplay,
  validateSplayTree,
  createLCTNode,
  createEmptyLCTForest,
  cloneLCTForest,
  isLCTAuxRoot,
  pushDownLCTNode,
  updateLCTNodeSize,
  pushDownLCTPath,
  rotateLCT,
  splayLCT,
  accessLCT,
  makeRootLCT,
  findRootLCT,
  linkLCT,
  cutLCT,
  getLCTPreferredEdges,
  getLCTPathParentEdges,
  generateCartesianOperationSteps,
  generateImplicitOperationSteps,
  generateSplayOperationSteps,
  generateLCTOperationSteps,
  layoutBinaryTree,
  layoutLCTForest,
} from "./TreapSplayTreeStudio";
export type {
  TreapSplayModality,
  TreapSplayPresetId,
  CartesianNode,
  ImplicitNode,
  SplayNode,
  SplayRotationType,
  LCTNode,
  LCTForest,
  TreapSplayTelemetry,
  TreapSplayAnimationStep,
  TreapSplayPreset,
  RenderNodeLayout,
  RenderEdgeLayout,
  SplayStepLog,
  TreapSplayTreeStudioProps,
} from "./TreapSplayTreeStudio";

export {
  RingAttentionStudio,
  RING_GPU_SPECS,
  RING_INTERCONNECT_SPECS,
  RING_ATTENTION_PRESETS,
  getBytesPerPrecision,
  computeOnlineSoftmaxStep,
  computeMonolithicAttention,
  generateSyntheticQKV,
  runOnlineSoftmaxSimulation,
  generateCausalTileSchedule,
  calculateRingRooflineProfile,
  generatePyTorchRingAttentionCode,
  generateZigZagPyTorchCode,
  generateTritonRingKernelCode,
  generateMegatronCPLaunchCommand,
  formatBytes as formatRingBytes,
  formatFLOPs as formatRingFLOPs,
  formatBandwidth as formatRingBandwidth,
  formatLatencyUs as formatRingLatencyUs,
  formatNumberWithCommas as formatRingNumberWithCommas,
} from "./RingAttentionStudio";
export type {
  RingPresetId,
  RingAttentionTabId,
  AttentionVariant,
  PrecisionFormat as RingPrecisionFormat,
  RingGpuSpec,
  RingInterconnectSpec,
  RingClusterConfig,
  RingAttentionPreset,
  OnlineSoftmaxHopTrace,
  OnlineSoftmaxVerificationResult,
  CausalTileInfo,
  CausalScheduleResult,
  RingRooflineResult,
  RingAttentionStudioProps,
} from "./RingAttentionStudio";

export {
  WassersteinGANStudio,
  SeededRNG as WGANSeededRNG,
  norm2D as norm2DWGAN,
  dist2D as dist2DWGAN,
  dot2D as dot2DWGAN,
  add2D as add2DWGAN,
  sub2D as sub2DWGAN,
  scale2D as scale2DWGAN,
  lerp2D as lerp2DWGAN,
  generateEightGaussians,
  generateTwentyFiveGaussians,
  generateSwissRoll as generateSwissRollWGAN,
  generateTwoMoons,
  generateConcentricRings,
  generatePinwheel,
  generateDatasetBatch,
  DATASET_DEFINITIONS as WGAN_DATASET_DEFINITIONS,
  createMLPLayer,
  createMLPNetwork,
  applyActivationFn,
  applyActivationDerivative,
  powerIterationSpectralNorm,
  updateSpectralNorm,
  clipWeights,
  forwardMLP,
  computeInputGradient,
  backwardMLP,
  createAdamState,
  stepAdam,
  createRMSPropState,
  stepRMSProp,
  computeKantorovichWasserstein,
  computeSlicedWassersteinDistance,
  computeJensenShannonDivergence,
  computeModeCoverageMetrics,
  computeVectorField,
  computeGPInterpolations,
  computeLipschitzGrid,
  trainGANStep,
  GAN_PARADIGM_INFOS,
  WGAN_STUDIO_PRESETS,
} from "./WassersteinGANStudio";
export type {
  Vector2 as WGANVector2,
  GANParadigmId,
  DatasetId as WGANDatasetId,
  StudioTabId as WGANStudioTabId,
  PresetId as WGANPresetId,
  DatasetModeInfo,
  DatasetBatch,
  MLPLayer,
  MLPNetwork,
  MLPForwardCache,
  AdamOptimizerState,
  RMSPropOptimizerState,
  GANTrainingState,
  MetricsSnapshot,
  VectorFieldPoint,
  GPInterpolationLine,
  PresetConfig as WGANPresetConfig,
  GANParadigmInfo,
  WassersteinGANStudioProps,
} from "./WassersteinGANStudio";

export {
  BipartiteMatchingStudio,
  MATCHING_MODALITY_INFOS,
  BIPARTITE_MATCHING_PRESETS,
  runHopcroftKarpAlgorithm,
  runKonigDuality,
  runHungarianAlgorithm,
  runHallConditionScanner,
} from "./BipartiteMatchingStudio";
export type {
  BipartiteStudioModality,
  BipartitePresetId,
  BipartiteNode,
  BipartiteEdge,
  BipartiteGraph,
  BipartiteStepAction,
  BipartiteTelemetry,
  BipartiteAnimationStep,
  BipartitePreset,
  ModalityConfig as BipartiteModalityConfig,
  BipartiteMatchingStudioProps,
} from "./BipartiteMatchingStudio";

export {
  FlashDecodingStudio,
  FLASH_DECODING_GPU_SPECS,
  FLASH_DECODING_PRESETS,
  getBytesPerPrecision as getBytesPerPrecisionFlash,
  formatBytes as formatFlashBytes,
  formatFlops as formatFlashFlops,
  formatBandwidth as formatFlashBandwidth,
  formatLatencyUs as formatFlashLatencyUs,
  formatNumberWithCommas as formatFlashNumberWithCommas,
  calculateSplitKParameters,
  computePartialSoftmaxSplit,
  mergePartialSoftmaxSplits,
  computeMonolithicAttentionDecode,
  buildTreeReductionGraph,
  generateSyntheticQKV as generateSyntheticQKVFlash,
  verifyFlashDecodingNumericAccuracy,
  calculateSmOccupancyAndWaves,
  calculateFlashDecodingRoofline,
  generateTritonFlashDecodingCode,
  generatePyTorchSplitKReferenceCode,
  generateCudaFlashDecodingHeader,
  generateVllmEngineLaunchCommand,
} from "./FlashDecodingStudio";
export type {
  FlashDecodingPresetId,
  FlashDecodingTabId,
  PrecisionFormat as FlashPrecisionFormat,
  GpuHardwareSpec as FlashDecodingGpuHardwareSpec,
  FlashDecodingConfig,
  FlashDecodingPreset,
  PartialSoftmaxSplit,
  TreeReductionNode,
  TreeReductionStage,
  NumericVerificationResult,
  SmOccupancyResult,
  RooflineBenchmarkResult,
  FlashDecodingStudioProps,
} from "./FlashDecodingStudio";

export {
  ContrastiveLearningStudio,
  SeededRNG as ContrastiveSeededRNG,
  dotProduct3D as dotProduct3DContrastive,
  norm3D as norm3DContrastive,
  normalize3D as normalize3DContrastive,
  euclideanDistance3D as euclideanDistance3DContrastive,
  cosineSimilarity as cosineSimilarityContrastive,
  projectOntoHypersphere,
  tangentSpaceProject,
  matrixVectorMultiply3x3,
  createIdentityMatrix3x3,
  compute3x3Eigenvalues,
  computeSingularValueSpectrum,
  sigmoid as sigmoidContrastive,
  computeSimCLRInfoNCELoss,
  computeWangIsolaAlignment,
  computeWangIsolaUniformity,
  computeBYOLLoss,
  computeSigLIPLoss,
  computeSimilarityMatrixData,
  PALETTE_COLORS as CONTRASTIVE_PALETTE_COLORS,
  CROSS_MODAL_CONCEPTS as CONTRASTIVE_CROSS_MODAL_CONCEPTS,
  generateImageTextDataset,
  generateAugmentationDataset,
  generateClusteredHypersphereDataset,
  generateHardNegativesDataset,
  generateDimensionalCollapseDataset,
  generateBenchmarkDataset as generateContrastiveBenchmarkDataset,
  CONTRASTIVE_PARADIGM_INFOS,
  BENCHMARK_DATASET_INFOS as CONTRASTIVE_BENCHMARK_DATASET_INFOS,
  CONTRASTIVE_STUDIO_PRESETS,
  stepContrastiveOptimization,
  project3DToHypersphereView,
} from "./ContrastiveLearningStudio";
export type {
  Vector3 as ContrastiveVector3,
  Vector2 as ContrastiveVector2,
  ContrastiveParadigmId,
  BenchmarkDatasetId as ContrastiveBenchmarkDatasetId,
  StudioTabId as ContrastiveStudioTabId,
  ContrastivePresetId,
  ProjectionMode as ContrastiveProjectionMode,
  ModalityType as ContrastiveModalityType,
  EmbeddingPoint as ContrastiveEmbeddingPoint,
  PositivePair as ContrastivePositivePair,
  AlgorithmHyperparameters as ContrastiveAlgorithmHyperparameters,
  OptimizationMetrics as ContrastiveOptimizationMetrics,
  OptimizationHistoryPoint as ContrastiveOptimizationHistoryPoint,
  OptimizationState as ContrastiveOptimizationState,
  Camera3D as ContrastiveCamera3D,
  SimilarityMatrixData as ContrastiveSimilarityMatrixData,
  EffectiveRankAnalysis as ContrastiveEffectiveRankAnalysis,
  ContrastivePreset,
  ContrastiveParadigmInfo,
  BenchmarkDatasetInfo as ContrastiveBenchmarkDatasetInfo,
  ContrastiveLearningStudioProps,
} from "./ContrastiveLearningStudio";

export {
  VoronoiDelaunayStudio,
  DEFAULT_CANVAS_WIDTH as VORONOI_DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT as VORONOI_DEFAULT_CANVAS_HEIGHT,
  DEFAULT_BOUNDS as VORONOI_DEFAULT_BOUNDS,
  PASTEL_PALETTE as VORONOI_PASTEL_PALETTE,
  VORONOI_MODALITIES,
  VORONOI_STUDIO_PRESETS,
  distance as voronoiDistance,
  distanceSq as voronoiDistanceSq,
  crossProduct2D as voronoiCrossProduct2D,
  isCCW as isCCWVoronoi,
  turnOrientation as voronoiTurnOrientation,
  computeCircumcircle,
  inCircumcircleDeterminant,
  inCircumcircle,
  clipPolygonWithBisector,
  computePolygonAreaAndCentroid,
  computeBowyerWatsonDelaunay,
  computeVoronoiDiagramFromDelaunay,
  computeLloydRelaxation,
  computeFortuneSweep,
  DisjointSetUnion,
  computeEMST,
  computeBruteForceMST,
  computeVoronoiStudioTelemetry,
} from "./VoronoiDelaunayStudio";
export type {
  VoronoiStudioModality,
  VoronoiPresetId,
  Point2D as VoronoiPoint2D,
  BoundingBox as VoronoiBoundingBox,
  Circumcircle as VoronoiCircumcircle,
  Triangle2D as VoronoiTriangle2D,
  DelaunayEdge,
  VoronoiEdge,
  VoronoiCell,
  BowyerWatsonAction,
  BowyerWatsonStep,
  BowyerWatsonResult,
  FortuneEventType,
  SiteEvent as VoronoiSiteEvent,
  CircleEvent as VoronoiCircleEvent,
  FortuneEvent as VoronoiFortuneEvent,
  BeachlineArc,
  FortuneSweepStep,
  EMSTEdgeStatus,
  EMSTEdge,
  EMSTStep,
  EMSTResult,
  VoronoiPreset,
  VoronoiStudioTelemetry,
  ModalityConfig as VoronoiModalityConfig,
  VoronoiDelaunayStudioProps,
} from "./VoronoiDelaunayStudio";

export {
  FlowMatchingStudio,
  DEFAULT_VIEW_BOUNDS as FLOW_MATCHING_DEFAULT_VIEW_BOUNDS,
  PALETTE as FLOW_MATCHING_PALETTE,
  FLOW_MATCHING_PRESETS,
  SeededRNG as FlowMatchingSeededRNG,
  add2D as flowMatchingAdd2D,
  sub2D as flowMatchingSub2D,
  scale2D as flowMatchingScale2D,
  dot2D as flowMatchingDot2D,
  normSq2D as flowMatchingNormSq2D,
  norm2D as flowMatchingNorm2D,
  distSq2D as flowMatchingDistSq2D,
  dist2D as flowMatchingDist2D,
  normalize2D as flowMatchingNormalize2D,
  generateFlowDataset,
  computeLinearPathPoint,
  computeConditionalTargetVelocity,
  computeIndependentCoupling,
  computeHungarianOTCoupling,
  computeSinkhornOTCoupling,
  computeTransportCost,
  computeTrajectoryStraightness,
  computeMarginalVectorField,
  computeAnalyticalDivergence,
  computeVectorFieldGrid,
  eulerStep,
  midpointStep,
  rk4Step,
  integrateODE,
  runODEBenchmark,
} from "./FlowMatchingStudio";
export type {
  Vector2 as FlowMatchingVector2,
  FlowDatasetId,
  CouplingType as FlowMatchingCouplingType,
  ODESolverType as FlowMatchingODESolverType,
  FlowStudioTabId as FlowMatchingStudioTabId,
  FlowPresetId as FlowMatchingPresetId,
  FlowPoint as FlowMatchingFlowPoint,
  CouplingPair as FlowMatchingCouplingPair,
  ParticleState as FlowMatchingParticleState,
  VectorFieldCell as FlowMatchingVectorFieldCell,
  SolverBenchmarkResult as FlowMatchingSolverBenchmarkResult,
  FlowMatchingPreset,
  FlowMatchingStudioProps,
} from "./FlowMatchingStudio";

export {
  KVCacheCompressionStudio,
  KV_CACHE_GPU_SPECS,
  KV_CACHE_PRESETS,
  calculateKvCacheMemoryBytes,
  calculateGroupQuantizationParams,
  simulateStreamingEviction,
  calculateServingCapacityAndLatency,
  formatBytes as formatKVCacheBytes,
  formatNumberWithCommas as formatKVCacheNumberWithCommas,
  formatLatencyMs as formatKVCacheLatencyMs,
  formatBandwidthGbps as formatKVCacheBandwidthGbps,
  formatTflops as formatKVCacheTflops,
  generateTritonQuantizedKvKernel,
  generateVllmServingConfig,
  generatePyTorchStreamingCacheReference,
  generateCudaDequantHeader,
} from "./KVCacheCompressionStudio";
export type {
  KVCachePresetId,
  KVCacheTabId,
  AttentionArchitecture as KVCacheAttentionArchitecture,
  KVCachePrecision,
  QuantizationScheme as KVCacheQuantizationScheme,
  INT4GroupSize as KVCacheINT4GroupSize,
  StreamingEvictionPolicy as KVCacheStreamingEvictionPolicy,
  TokenRole as KVCacheTokenRole,
  GpuHardwareSpec as KVCacheGpuHardwareSpec,
  KVCacheModelConfig,
  KVCachePreset,
  QuantizationResult as KVCacheQuantizationResult,
  StreamingSimulationStep as KVCacheStreamingSimulationStep,
  StreamingSimulationResult as KVCacheStreamingSimulationResult,
  ServingWaterfallBudget as KVCacheServingWaterfallBudget,
  ServingPerformanceMetrics as KVCacheServingPerformanceMetrics,
  KVCacheStudioProps,
} from "./KVCacheCompressionStudio";

export {
  ConvexHullTrickStudio,
  computeLineIntersection as computeCHTStudioLineIntersection,
  buildMonotonicCHT,
  queryMonotonicCHT,
  buildDynamicCHT,
  queryDynamicCHT,
  buildLiChaoTree,
  queryLiChaoTree,
  solveKnuthDP,
  verifyMongeProperty,
  CHT_MODALITIES,
  CHT_PRESETS as CHT_STUDIO_PRESETS,
  DYNAMIC_CHT_PRESETS,
  LICHAO_PRESETS,
  KNUTH_PRESETS,
} from "./ConvexHullTrickStudio";
export type {
  CHTStudioModality,
  OptimizationType,
  CHTLine as CHTStudioLine,
  LineIntersection,
  CHTQueryResult as CHTStudioQueryResult,
  MonotonicCHTStep,
  MonotonicCHTResult,
  DynamicCHTStep,
  DynamicCHTResult,
  LiChaoNode,
  LiChaoTreeStep,
  LiChaoTreeResult,
  KnuthDPStep,
  MongeViolation,
  MongeVerificationResult,
  KnuthDPResult,
  ConvexHullTrickStudioProps,
} from "./ConvexHullTrickStudio";
